site_name: plotnine-prism
repo_url: https://github.com/pwwang/plotnine-prism
repo_name: pwwang/plotnine-prism
theme:
    # favicon: favicon.png
    # logo: favicon.png
    icon:
        repo: fontawesome/brands/github
    palette:
        primary: black
    name: 'material'
    # font:
    #   text: 'Ubuntu'
    #   code: 'Ubuntu Mono'
    features:
        - navigation.top
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
plugins:
    - search # necessary for search to work
    - mkapi
    - mkdocs-jupyter:
        execute: false
        # execute: true
extra_css:
    - style.css
nav:
    - 'Home': 'index.md'
    - 'Getting Started': 'raw/get_started.ipynb'
    - 'Guides':
        'Themes': 'raw/themes.ipynb'
        'Color, Fill and Shape Palettes': 'raw/colours.ipynb'
        'Changing Axes': 'raw/axes.ipynb'
    - 'Examples':
        'Dose Reponse Curve': 'raw/ex1-dose.ipynb'
    - 'API': 'mkapi/api/plotnine_prism'
    - 'Change Log': CHANGELOG.md
