# https://plotnine.readthedocs.io/en/stable/_modules/plotnine/scales/scale_shape.html
complete = [
    'o', # { name = "circle small", pch = 16.0 },
    's', # { name = "square", pch = 15.0 },
    '^', # { name = "triangle", pch = 17.0 },
    'd', # { name = "diamond", pch = 18.0 },
    'p', # { name = "circle filled", pch = 21.0 },
    'H', # { name = "square filled", pch = 22.0 },
    'v', # { name = "triangle filled", pch = 24.0 },
    '^', # { name = "triangle down filled", pch = 25.0 },
    'D', # { name = "diamond filled", pch = 23.0 },
    '*', # { name = "asterisk", pch = 8.0 },
    '+', # { name = "plus", pch = 3.0 },
    '_', # { name = "cross", pch = 4.0 },
    '8', # { name = "circle plus", pch = 10.0 },
    'x', # { name = "square cross", pch = 7.0 },
]
default = [
    'o',  # { name = "circle small", pch = 16.0 },
    's',  # { name = "square", pch = 15.0 },
    '^',  # { name = "triangle", pch = 17.0 },
    'd',  # { name = "diamond", pch = 18.0 },
    '*',  # { name = "asterisk", pch = 8.0 },
    '+',  # { name = "plus", pch = 3.0 },
    '_',  # { name = "cross", pch = 4.0 },
    '8',  # { name = "circle plus", pch = 10.0 },
    'x',  # { name = "square cross", pch = 7.0 },
]
filled = [
    'o', # { name = "circle filled", pch = 21.0 },
    's', # { name = "square filled", pch = 22.0 },
    'v', # { name = "triangle filled", pch = 24.0 },
    '^', # { name = "triangle down filled", pch = 25.0 },
    'D', # { name = "diamond filled", pch = 23.0 },
    '*', # { name = "asterisk", pch = 8.0 },
    '+', # { name = "plus", pch = 3.0 },
    '_', # { name = "cross", pch = 4.0 },
    '8', # { name = "circle plus", pch = 10.0 },
    'x', # { name = "square cross", pch = 7.0 },
]
