pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#A00000"
axisLabelColor = "#A00000"
axisTitleColor = "#A00000"
graphTitleColor = "#A00000"
objectTextColor = "#A00000"
objectFillColor = "#FFFFFF"
objectBorderColor = "#A00000"
objectLinesColor = "#A00000"
objectPatternColor = "#A00000"
embeddedTableBorderColor = "#A00000"
embeddedTableLineUnderTitleColor = "#A00000"
embeddedTableLineNextToRowTitleColor = "#A00000"
embeddedTableTextColor = "#A00000"
embeddedTableGridColor = "#A00000"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#A00000"
dataSetBarPatternColor1 = "#A00000"
dataSetFillColor1 = "#A00000"
dataSetLineColor1 = "#A00000"
dataSetBorderColor1 = "#A00000"
dataSetBackgroundColor1 = "#A00000"
dataSetErrorColor1 = "#A00000"
dataSetLegendColor1 = "#A00000"
dataSetRowTitleColor1 = "#A00000"
dataSetBarFillColor2 = "#FF0000"
dataSetBarPatternColor2 = "#FF0000"
dataSetFillColor2 = "#FF0000"
dataSetLineColor2 = "#FF0000"
dataSetBorderColor2 = "#FF0000"
dataSetBackgroundColor2 = "#FF0000"
dataSetErrorColor2 = "#FF0000"
dataSetLegendColor2 = "#A00000"
dataSetRowTitleColor2 = "#A00000"
dataSetBarFillColor3 = "#CE0665"
dataSetBarPatternColor3 = "#CE0665"
dataSetFillColor3 = "#CE0665"
dataSetLineColor3 = "#CE0665"
dataSetBorderColor3 = "#CE0665"
dataSetBackgroundColor3 = "#CE0665"
dataSetErrorColor3 = "#CE0665"
dataSetLegendColor3 = "#A00000"
dataSetRowTitleColor3 = "#A00000"
dataSetBarFillColor4 = "#FF8080"
dataSetBarPatternColor4 = "#FF8080"
dataSetFillColor4 = "#FF8080"
dataSetLineColor4 = "#FF8080"
dataSetBorderColor4 = "#FF8080"
dataSetBackgroundColor4 = "#FF8080"
dataSetErrorColor4 = "#FF8080"
dataSetLegendColor4 = "#A00000"
dataSetRowTitleColor4 = "#A00000"
dataSetBarFillColor5 = "#9F044D"
dataSetBarPatternColor5 = "#9F044D"
dataSetFillColor5 = "#9F044D"
dataSetLineColor5 = "#9F044D"
dataSetBorderColor5 = "#9F044D"
dataSetBackgroundColor5 = "#9F044D"
dataSetErrorColor5 = "#9F044D"
dataSetLegendColor5 = "#A00000"
dataSetRowTitleColor5 = "#A00000"
dataSetBarFillColor6 = "#F94040"
dataSetBarPatternColor6 = "#F94040"
dataSetFillColor6 = "#F94040"
dataSetLineColor6 = "#F94040"
dataSetBorderColor6 = "#F94040"
dataSetBackgroundColor6 = "#F94040"
dataSetErrorColor6 = "#F94040"
dataSetLegendColor6 = "#A00000"
dataSetRowTitleColor6 = "#A00000"
dataSetBarFillColor7 = "#FF6000"
dataSetBarPatternColor7 = "#FF6000"
dataSetFillColor7 = "#FF6000"
dataSetLineColor7 = "#FF6000"
dataSetBorderColor7 = "#FF6000"
dataSetBackgroundColor7 = "#FF6000"
dataSetErrorColor7 = "#FF6000"
dataSetLegendColor7 = "#A00000"
dataSetRowTitleColor7 = "#A00000"
dataSetBarFillColor8 = "#CE0665"
dataSetBarPatternColor8 = "#CE0665"
dataSetFillColor8 = "#CE0665"
dataSetLineColor8 = "#CE0665"
dataSetBorderColor8 = "#CE0665"
dataSetBackgroundColor8 = "#CE0665"
dataSetErrorColor8 = "#CE0665"
dataSetLegendColor8 = "#A00000"
dataSetRowTitleColor8 = "#A00000"
dataSetBarFillColor9 = "#C06000"
dataSetBarPatternColor9 = "#C06000"
dataSetFillColor9 = "#C06000"
dataSetLineColor9 = "#C06000"
dataSetBorderColor9 = "#C06000"
dataSetBackgroundColor9 = "#C06000"
dataSetErrorColor9 = "#C06000"
dataSetLegendColor9 = "#A00000"
dataSetRowTitleColor9 = "#A00000"
