pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#A00000"
axisLabelColor = "#A00000"
axisTitleColor = "#A00000"
graphTitleColor = "#A00000"
objectTextColor = "#A00000"
objectFillColor = "#FFFFFF"
objectBorderColor = "#A00000"
objectLinesColor = "#A00000"
objectPatternColor = "#A00000"
embeddedTableBorderColor = "#A00000"
embeddedTableLineUnderTitleColor = "#A00000"
embeddedTableLineNextToRowTitleColor = "#A00000"
embeddedTableTextColor = "#A00000"
embeddedTableGridColor = "#A00000"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#94641F"
dataSetBarPatternColor1 = "#94641F"
dataSetFillColor1 = "#94641F"
dataSetLineColor1 = "#94641F"
dataSetBorderColor1 = "#94641F"
dataSetBackgroundColor1 = "#94641F"
dataSetErrorColor1 = "#94641F"
dataSetLegendColor1 = "#A00000"
dataSetRowTitleColor1 = "#A00000"
dataSetBarFillColor2 = "#C5944E"
dataSetBarPatternColor2 = "#C5944E"
dataSetFillColor2 = "#C5944E"
dataSetLineColor2 = "#C5944E"
dataSetBorderColor2 = "#C5944E"
dataSetBackgroundColor2 = "#C5944E"
dataSetErrorColor2 = "#C5944E"
dataSetLegendColor2 = "#A00000"
dataSetRowTitleColor2 = "#A00000"
dataSetBarFillColor3 = "#D79A40"
dataSetBarPatternColor3 = "#D79A40"
dataSetFillColor3 = "#D79A40"
dataSetLineColor3 = "#D79A40"
dataSetBorderColor3 = "#D79A40"
dataSetBackgroundColor3 = "#D79A40"
dataSetErrorColor3 = "#D79A40"
dataSetLegendColor3 = "#A00000"
dataSetRowTitleColor3 = "#A00000"
dataSetBarFillColor4 = "#C0B57B"
dataSetBarPatternColor4 = "#C0B57B"
dataSetFillColor4 = "#C0B57B"
dataSetLineColor4 = "#C0B57B"
dataSetBorderColor4 = "#C0B57B"
dataSetBackgroundColor4 = "#C0B57B"
dataSetErrorColor4 = "#C0B57B"
dataSetLegendColor4 = "#A00000"
dataSetRowTitleColor4 = "#A00000"
dataSetBarFillColor5 = "#804040"
dataSetBarPatternColor5 = "#804040"
dataSetFillColor5 = "#804040"
dataSetLineColor5 = "#804040"
dataSetBorderColor5 = "#804040"
dataSetBackgroundColor5 = "#804040"
dataSetErrorColor5 = "#804040"
dataSetLegendColor5 = "#A00000"
dataSetRowTitleColor5 = "#A00000"
dataSetBarFillColor6 = "#BB5E00"
dataSetBarPatternColor6 = "#BB5E00"
dataSetFillColor6 = "#BB5E00"
dataSetLineColor6 = "#BB5E00"
dataSetBorderColor6 = "#BB5E00"
dataSetBackgroundColor6 = "#BB5E00"
dataSetErrorColor6 = "#BB5E00"
dataSetLegendColor6 = "#A00000"
dataSetRowTitleColor6 = "#A00000"
dataSetBarFillColor7 = "#CD751D"
dataSetBarPatternColor7 = "#CD751D"
dataSetFillColor7 = "#CD751D"
dataSetLineColor7 = "#CD751D"
dataSetBorderColor7 = "#CD751D"
dataSetBackgroundColor7 = "#CD751D"
dataSetErrorColor7 = "#CD751D"
dataSetLegendColor7 = "#A00000"
dataSetRowTitleColor7 = "#A00000"
dataSetBarFillColor8 = "#910000"
dataSetBarPatternColor8 = "#910000"
dataSetFillColor8 = "#910000"
dataSetLineColor8 = "#910000"
dataSetBorderColor8 = "#910000"
dataSetBackgroundColor8 = "#910000"
dataSetErrorColor8 = "#910000"
dataSetLegendColor8 = "#A00000"
dataSetRowTitleColor8 = "#A00000"
dataSetBarFillColor9 = "#A25100"
dataSetBarPatternColor9 = "#A25100"
dataSetFillColor9 = "#A25100"
dataSetLineColor9 = "#A25100"
dataSetBorderColor9 = "#A25100"
dataSetBackgroundColor9 = "#A25100"
dataSetErrorColor9 = "#A25100"
dataSetLegendColor9 = "#A00000"
dataSetRowTitleColor9 = "#A00000"
