pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#000000"
axisLabelColor = "#000000"
axisTitleColor = "#000000"
graphTitleColor = "#000000"
objectTextColor = "#000000"
objectFillColor = "#FFFFFF"
objectBorderColor = "#000000"
objectLinesColor = "#000000"
objectPatternColor = "#000000"
embeddedTableBorderColor = "#000000"
embeddedTableLineUnderTitleColor = "#000000"
embeddedTableLineNextToRowTitleColor = "#000000"
embeddedTableTextColor = "#000000"
embeddedTableGridColor = "#000000"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#000000"
dataSetBarPatternColor1 = "#000000"
dataSetFillColor1 = "#000000"
dataSetLineColor1 = "#000000"
dataSetBorderColor1 = "#000000"
dataSetBackgroundColor1 = "#000000"
dataSetErrorColor1 = "#000000"
dataSetLegendColor1 = "#000000"
dataSetRowTitleColor1 = "#000000"
dataSetBarFillColor2 = "#A0A0A4"
dataSetBarPatternColor2 = "#A0A0A4"
dataSetFillColor2 = "#000000"
dataSetLineColor2 = "#000000"
dataSetBorderColor2 = "#A0A0A4"
dataSetBackgroundColor2 = "#A0A0A4"
dataSetErrorColor2 = "#000000"
dataSetLegendColor2 = "#000000"
dataSetRowTitleColor2 = "#000000"
dataSetBarFillColor3 = "#808080"
dataSetBarPatternColor3 = "#808080"
dataSetFillColor3 = "#000000"
dataSetLineColor3 = "#000000"
dataSetBorderColor3 = "#808080"
dataSetBackgroundColor3 = "#808080"
dataSetErrorColor3 = "#000000"
dataSetLegendColor3 = "#000000"
dataSetRowTitleColor3 = "#000000"
dataSetBarFillColor4 = "#D4D4D4"
dataSetBarPatternColor4 = "#D4D4D4"
dataSetFillColor4 = "#000000"
dataSetLineColor4 = "#000000"
dataSetBorderColor4 = "#D4D4D4"
dataSetBackgroundColor4 = "#D4D4D4"
dataSetErrorColor4 = "#000000"
dataSetLegendColor4 = "#000000"
dataSetRowTitleColor4 = "#000000"
dataSetBarFillColor5 = "#606060"
dataSetBarPatternColor5 = "#606060"
dataSetFillColor5 = "#000000"
dataSetLineColor5 = "#000000"
dataSetBorderColor5 = "#606060"
dataSetBackgroundColor5 = "#606060"
dataSetErrorColor5 = "#000000"
dataSetLegendColor5 = "#000000"
dataSetRowTitleColor5 = "#000000"
dataSetBarFillColor6 = "#A0A0A4"
dataSetBarPatternColor6 = "#A0A0A4"
dataSetFillColor6 = "#000000"
dataSetLineColor6 = "#000000"
dataSetBorderColor6 = "#A0A0A4"
dataSetBackgroundColor6 = "#A0A0A4"
dataSetErrorColor6 = "#000000"
dataSetLegendColor6 = "#000000"
dataSetRowTitleColor6 = "#000000"
dataSetBarFillColor7 = "#606060"
dataSetBarPatternColor7 = "#606060"
dataSetFillColor7 = "#000000"
dataSetLineColor7 = "#000000"
dataSetBorderColor7 = "#606060"
dataSetBackgroundColor7 = "#606060"
dataSetErrorColor7 = "#000000"
dataSetLegendColor7 = "#000000"
dataSetRowTitleColor7 = "#000000"
dataSetBarFillColor8 = "#E8E8E8"
dataSetBarPatternColor8 = "#E8E8E8"
dataSetFillColor8 = "#000000"
dataSetLineColor8 = "#000000"
dataSetBorderColor8 = "#E8E8E8"
dataSetBackgroundColor8 = "#E8E8E8"
dataSetErrorColor8 = "#000000"
dataSetLegendColor8 = "#000000"
dataSetRowTitleColor8 = "#000000"
dataSetBarFillColor9 = "#A0A0A4"
dataSetBarPatternColor9 = "#A0A0A4"
dataSetFillColor9 = "#000000"
dataSetLineColor9 = "#000000"
dataSetBorderColor9 = "#A0A0A4"
dataSetBackgroundColor9 = "#A0A0A4"
dataSetErrorColor9 = "#000000"
dataSetLegendColor9 = "#000000"
dataSetRowTitleColor9 = "#000000"
