pageBackgroundColor = "#6699CC"
plottingAreaColor = "#FFFFFF"
axisColor = "#FFFFFF"
axisLabelColor = "#FFFFFF"
axisTitleColor = "#FFFFFF"
graphTitleColor = "#FFFFFF"
objectTextColor = "#FFFFFF"
objectFillColor = "#FFFFFF"
objectBorderColor = "#FFFFFF"
objectLinesColor = "#FFFFFF"
objectPatternColor = "#FFFFFF"
embeddedTableBorderColor = "#FFFFFF"
embeddedTableLineUnderTitleColor = "#FFFFFF"
embeddedTableLineNextToRowTitleColor = "#FFFFFF"
embeddedTableTextColor = "#FFFFFF"
embeddedTableGridColor = "#FFFFFF"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#FFFFFF"
dataSetBarPatternColor1 = "#FFFFFF"
dataSetFillColor1 = "#FFFFFF"
dataSetLineColor1 = "#FFFFFF"
dataSetBorderColor1 = "#FFFFFF"
dataSetBackgroundColor1 = "#FFFFFF"
dataSetErrorColor1 = "#FFFFFF"
dataSetLegendColor1 = "#FFFFFF"
dataSetRowTitleColor1 = "#FFFFFF"
dataSetBarFillColor2 = "#C8DEF9"
dataSetBarPatternColor2 = "#C8DEF9"
dataSetFillColor2 = "#C8DEF9"
dataSetLineColor2 = "#C8DEF9"
dataSetBorderColor2 = "#366699"
dataSetBackgroundColor2 = "#C8DEF9"
dataSetErrorColor2 = "#FFFFFF"
dataSetLegendColor2 = "#FFFFFF"
dataSetRowTitleColor2 = "#FFFFFF"
dataSetBarFillColor3 = "#FFFFFF"
dataSetBarPatternColor3 = "#FFFFFF"
dataSetFillColor3 = "#FFFFFF"
dataSetLineColor3 = "#FFFFFF"
dataSetBorderColor3 = "#FFFFFF"
dataSetBackgroundColor3 = "#FFFFFF"
dataSetErrorColor3 = "#FFFFFF"
dataSetLegendColor3 = "#FFFFFF"
dataSetRowTitleColor3 = "#FFFFFF"
dataSetBarFillColor4 = "#FFFFFF"
dataSetBarPatternColor4 = "#FFFFFF"
dataSetFillColor4 = "#FFFFFF"
dataSetLineColor4 = "#FFFFFF"
dataSetBorderColor4 = "#366699"
dataSetBackgroundColor4 = "#FFFFFF"
dataSetErrorColor4 = "#366699"
dataSetLegendColor4 = "#FFFFFF"
dataSetRowTitleColor4 = "#FFFFFF"
dataSetBarFillColor5 = "#99CCFF"
dataSetBarPatternColor5 = "#99CCFF"
dataSetFillColor5 = "#99CCFF"
dataSetLineColor5 = "#99CCFF"
dataSetBorderColor5 = "#366699"
dataSetBackgroundColor5 = "#99CCFF"
dataSetErrorColor5 = "#366699"
dataSetLegendColor5 = "#FFFFFF"
dataSetRowTitleColor5 = "#FFFFFF"
dataSetBarFillColor6 = "#366699"
dataSetBarPatternColor6 = "#366699"
dataSetFillColor6 = "#366699"
dataSetLineColor6 = "#FFFFFF"
dataSetBorderColor6 = "#366699"
dataSetBackgroundColor6 = "#366699"
dataSetErrorColor6 = "#366699"
dataSetLegendColor6 = "#FFFFFF"
dataSetRowTitleColor6 = "#FFFFFF"
dataSetBarFillColor7 = "#FFFFFF"
dataSetBarPatternColor7 = "#FFFFFF"
dataSetFillColor7 = "#FFFFFF"
dataSetLineColor7 = "#FFFFFF"
dataSetBorderColor7 = "#000000"
dataSetBackgroundColor7 = "#FFFFFF"
dataSetErrorColor7 = "#000000"
dataSetLegendColor7 = "#FFFFFF"
dataSetRowTitleColor7 = "#FFFFFF"
dataSetBarFillColor8 = "#366699"
dataSetBarPatternColor8 = "#366699"
dataSetFillColor8 = "#366699"
dataSetLineColor8 = "#366699"
dataSetBorderColor8 = "#000000"
dataSetBackgroundColor8 = "#366699"
dataSetErrorColor8 = "#000000"
dataSetLegendColor8 = "#FFFFFF"
dataSetRowTitleColor8 = "#FFFFFF"
dataSetBarFillColor9 = "#003366"
dataSetBarPatternColor9 = "#003366"
dataSetFillColor9 = "#003366"
dataSetLineColor9 = "#FFFFFF"
dataSetBorderColor9 = "#003366"
dataSetBackgroundColor9 = "#003366"
dataSetErrorColor9 = "#003366"
dataSetLegendColor9 = "#FFFFFF"
dataSetRowTitleColor9 = "#FFFFFF"
