pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#363C81"
axisLabelColor = "#323232"
axisTitleColor = "#000000"
graphTitleColor = "#000000"
objectTextColor = "#27273D"
objectFillColor = "#FFFFFF"
objectBorderColor = "#7676A5"
objectLinesColor = "#474778"
objectPatternColor = "#C6C6C6"
embeddedTableBorderColor = "#323232"
embeddedTableLineUnderTitleColor = "#323232"
embeddedTableLineNextToRowTitleColor = "#323232"
embeddedTableTextColor = "#323232"
embeddedTableGridColor = "#323232"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#F3F3F3"
dataSetBarFillColor1 = "#F71480"
dataSetBarPatternColor1 = "#F71480"
dataSetFillColor1 = "#F71480"
dataSetLineColor1 = "#F71480"
dataSetBorderColor1 = "#F71480"
dataSetBackgroundColor1 = "#F71480"
dataSetErrorColor1 = "#F71480"
dataSetLegendColor1 = "#000080"
dataSetRowTitleColor1 = "#000080"
dataSetBarFillColor2 = "#FF8000"
dataSetBarPatternColor2 = "#FF8000"
dataSetFillColor2 = "#FF8000"
dataSetLineColor2 = "#FF8000"
dataSetBorderColor2 = "#FF8000"
dataSetBackgroundColor2 = "#FF8000"
dataSetErrorColor2 = "#FF8000"
dataSetLegendColor2 = "#000080"
dataSetRowTitleColor2 = "#000080"
dataSetBarFillColor3 = "#808000"
dataSetBarPatternColor3 = "#808000"
dataSetFillColor3 = "#808000"
dataSetLineColor3 = "#808000"
dataSetBorderColor3 = "#808000"
dataSetBackgroundColor3 = "#808000"
dataSetErrorColor3 = "#808000"
dataSetLegendColor3 = "#000080"
dataSetRowTitleColor3 = "#000080"
dataSetBarFillColor4 = "#008000"
dataSetBarPatternColor4 = "#008000"
dataSetFillColor4 = "#008000"
dataSetLineColor4 = "#008000"
dataSetBorderColor4 = "#008000"
dataSetBackgroundColor4 = "#008000"
dataSetErrorColor4 = "#008000"
dataSetLegendColor4 = "#000080"
dataSetRowTitleColor4 = "#000080"
dataSetBarFillColor5 = "#0000FF"
dataSetBarPatternColor5 = "#0000FF"
dataSetFillColor5 = "#0000FF"
dataSetLineColor5 = "#0000FF"
dataSetBorderColor5 = "#0000FF"
dataSetBackgroundColor5 = "#0000FF"
dataSetErrorColor5 = "#0000FF"
dataSetLegendColor5 = "#000080"
dataSetRowTitleColor5 = "#000080"
dataSetBarFillColor6 = "#76069A"
dataSetBarPatternColor6 = "#76069A"
dataSetFillColor6 = "#76069A"
dataSetLineColor6 = "#76069A"
dataSetBorderColor6 = "#76069A"
dataSetBackgroundColor6 = "#76069A"
dataSetErrorColor6 = "#76069A"
dataSetLegendColor6 = "#000080"
dataSetRowTitleColor6 = "#000080"
dataSetBarFillColor7 = "#F71480"
dataSetBarPatternColor7 = "#F71480"
dataSetFillColor7 = "#F71480"
dataSetLineColor7 = "#F71480"
dataSetBorderColor7 = "#F71480"
dataSetBackgroundColor7 = "#F71480"
dataSetErrorColor7 = "#F71480"
dataSetLegendColor7 = "#000080"
dataSetRowTitleColor7 = "#000080"
dataSetBarFillColor8 = "#FF8000"
dataSetBarPatternColor8 = "#FF8000"
dataSetFillColor8 = "#FF8000"
dataSetLineColor8 = "#FF8000"
dataSetBorderColor8 = "#FF8000"
dataSetBackgroundColor8 = "#FF8000"
dataSetErrorColor8 = "#FF8000"
dataSetLegendColor8 = "#000080"
dataSetRowTitleColor8 = "#000080"
dataSetBarFillColor9 = "#808000"
dataSetBarPatternColor9 = "#808000"
dataSetFillColor9 = "#808000"
dataSetLineColor9 = "#808000"
dataSetBorderColor9 = "#808000"
dataSetBackgroundColor9 = "#808000"
dataSetErrorColor9 = "#808000"
dataSetLegendColor9 = "#000080"
dataSetRowTitleColor9 = "#000080"
