pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#0000C0"
axisLabelColor = "#0000C0"
axisTitleColor = "#0000C0"
graphTitleColor = "#0000C0"
objectTextColor = "#0000C0"
objectFillColor = "#FFFFFF"
objectBorderColor = "#7676A5"
objectLinesColor = "#474778"
objectPatternColor = "#C6C6C6"
embeddedTableBorderColor = "#0000C0"
embeddedTableLineUnderTitleColor = "#0000C0"
embeddedTableLineNextToRowTitleColor = "#0000C0"
embeddedTableTextColor = "#0000C0"
embeddedTableGridColor = "#0000C0"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#F3F3F3"
dataSetBarFillColor1 = "#FF8080"
dataSetBarPatternColor1 = "#FF8080"
dataSetFillColor1 = "#FF8080"
dataSetLineColor1 = "#FF8080"
dataSetBorderColor1 = "#FF8080"
dataSetBackgroundColor1 = "#FF8080"
dataSetErrorColor1 = "#FF8080"
dataSetLegendColor1 = "#0000C0"
dataSetRowTitleColor1 = "#0000C0"
dataSetBarFillColor2 = "#FFA040"
dataSetBarPatternColor2 = "#FFA040"
dataSetFillColor2 = "#FFA040"
dataSetLineColor2 = "#FFA040"
dataSetBorderColor2 = "#FFA040"
dataSetBackgroundColor2 = "#FFA040"
dataSetErrorColor2 = "#FFA040"
dataSetLegendColor2 = "#0000C0"
dataSetRowTitleColor2 = "#0000C0"
dataSetBarFillColor3 = "#C0C000"
dataSetBarPatternColor3 = "#C0C000"
dataSetFillColor3 = "#C0C000"
dataSetLineColor3 = "#C0C000"
dataSetBorderColor3 = "#C0C000"
dataSetBackgroundColor3 = "#C0C000"
dataSetErrorColor3 = "#C0C000"
dataSetLegendColor3 = "#0000C0"
dataSetRowTitleColor3 = "#0000C0"
dataSetBarFillColor4 = "#00C000"
dataSetBarPatternColor4 = "#00C000"
dataSetFillColor4 = "#00C000"
dataSetLineColor4 = "#00C000"
dataSetBorderColor4 = "#00C000"
dataSetBackgroundColor4 = "#00C000"
dataSetErrorColor4 = "#00C000"
dataSetLegendColor4 = "#0000C0"
dataSetRowTitleColor4 = "#0000C0"
dataSetBarFillColor5 = "#55A0FB"
dataSetBarPatternColor5 = "#55A0FB"
dataSetFillColor5 = "#55A0FB"
dataSetLineColor5 = "#55A0FB"
dataSetBorderColor5 = "#55A0FB"
dataSetBackgroundColor5 = "#55A0FB"
dataSetErrorColor5 = "#55A0FB"
dataSetLegendColor5 = "#0000C0"
dataSetRowTitleColor5 = "#0000C0"
dataSetBarFillColor6 = "#AD07E3"
dataSetBarPatternColor6 = "#AD07E3"
dataSetFillColor6 = "#AD07E3"
dataSetLineColor6 = "#AD07E3"
dataSetBorderColor6 = "#AD07E3"
dataSetBackgroundColor6 = "#AD07E3"
dataSetErrorColor6 = "#AD07E3"
dataSetLegendColor6 = "#0000C0"
dataSetRowTitleColor6 = "#0000C0"
dataSetBarFillColor7 = "#FF8080"
dataSetBarPatternColor7 = "#FF8080"
dataSetFillColor7 = "#FF8080"
dataSetLineColor7 = "#FF8080"
dataSetBorderColor7 = "#FF8080"
dataSetBackgroundColor7 = "#FF8080"
dataSetErrorColor7 = "#FF8080"
dataSetLegendColor7 = "#0000C0"
dataSetRowTitleColor7 = "#0000C0"
dataSetBarFillColor8 = "#FFA040"
dataSetBarPatternColor8 = "#FFA040"
dataSetFillColor8 = "#FFA040"
dataSetLineColor8 = "#FFA040"
dataSetBorderColor8 = "#FFA040"
dataSetBackgroundColor8 = "#FFA040"
dataSetErrorColor8 = "#FFA040"
dataSetLegendColor8 = "#0000C0"
dataSetRowTitleColor8 = "#0000C0"
dataSetBarFillColor9 = "#C0C000"
dataSetBarPatternColor9 = "#C0C000"
dataSetFillColor9 = "#C0C000"
dataSetLineColor9 = "#C0C000"
dataSetBorderColor9 = "#C0C000"
dataSetBackgroundColor9 = "#C0C000"
dataSetErrorColor9 = "#C0C000"
dataSetLegendColor9 = "#0000C0"
dataSetRowTitleColor9 = "#0000C0"
