pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#000000"
axisLabelColor = "#000000"
axisTitleColor = "#000000"
graphTitleColor = "#000000"
objectTextColor = "#000000"
objectFillColor = "#FFFFFF"
objectBorderColor = "#000000"
objectLinesColor = "#000000"
objectPatternColor = "#000000"
embeddedTableBorderColor = "#000000"
embeddedTableLineUnderTitleColor = "#000000"
embeddedTableLineNextToRowTitleColor = "#000000"
embeddedTableTextColor = "#000000"
embeddedTableGridColor = "#000000"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#000000"
dataSetBarPatternColor1 = "#000000"
dataSetFillColor1 = "#000000"
dataSetLineColor1 = "#000000"
dataSetBorderColor1 = "#000000"
dataSetBackgroundColor1 = "#000000"
dataSetErrorColor1 = "#000000"
dataSetLegendColor1 = "#000000"
dataSetRowTitleColor1 = "#000000"
dataSetBarFillColor2 = "#FF0066"
dataSetBarPatternColor2 = "#FF0066"
dataSetFillColor2 = "#FF0066"
dataSetLineColor2 = "#FF0066"
dataSetBorderColor2 = "#FF0066"
dataSetBackgroundColor2 = "#FF0066"
dataSetErrorColor2 = "#FF0066"
dataSetLegendColor2 = "#000000"
dataSetRowTitleColor2 = "#000000"
dataSetBarFillColor3 = "#107F80"
dataSetBarPatternColor3 = "#107F80"
dataSetFillColor3 = "#107F80"
dataSetLineColor3 = "#107F80"
dataSetBorderColor3 = "#107F80"
dataSetBackgroundColor3 = "#107F80"
dataSetErrorColor3 = "#107F80"
dataSetLegendColor3 = "#000000"
dataSetRowTitleColor3 = "#000000"
dataSetBarFillColor4 = "#40007F"
dataSetBarPatternColor4 = "#40007F"
dataSetFillColor4 = "#40007F"
dataSetLineColor4 = "#40007F"
dataSetBorderColor4 = "#40007F"
dataSetBackgroundColor4 = "#40007F"
dataSetErrorColor4 = "#40007F"
dataSetLegendColor4 = "#000000"
dataSetRowTitleColor4 = "#000000"
dataSetBarFillColor5 = "#AA66FF"
dataSetBarPatternColor5 = "#AA66FF"
dataSetFillColor5 = "#AA66FF"
dataSetLineColor5 = "#AA66FF"
dataSetBorderColor5 = "#AA66FF"
dataSetBackgroundColor5 = "#AA66FF"
dataSetErrorColor5 = "#AA66FF"
dataSetLegendColor5 = "#000000"
dataSetRowTitleColor5 = "#000000"
dataSetBarFillColor6 = "#66CCFE"
dataSetBarPatternColor6 = "#66CCFE"
dataSetFillColor6 = "#66CCFE"
dataSetLineColor6 = "#66CCFE"
dataSetBorderColor6 = "#66CCFE"
dataSetBackgroundColor6 = "#66CCFE"
dataSetErrorColor6 = "#66CCFE"
dataSetLegendColor6 = "#000000"
dataSetRowTitleColor6 = "#000000"
