pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#000000"
axisLabelColor = "#000000"
axisTitleColor = "#000000"
graphTitleColor = "#000000"
objectTextColor = "#000000"
objectFillColor = "#FFFFFF"
objectBorderColor = "#000000"
objectLinesColor = "#000000"
objectPatternColor = "#000000"
embeddedTableBorderColor = "#000000"
embeddedTableLineUnderTitleColor = "#000000"
embeddedTableLineNextToRowTitleColor = "#000000"
embeddedTableTextColor = "#000000"
embeddedTableGridColor = "#000000"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#0000FF"
dataSetBarPatternColor1 = "#0000FF"
dataSetFillColor1 = "#0000FF"
dataSetLineColor1 = "#0000FF"
dataSetBorderColor1 = "#0000FF"
dataSetBackgroundColor1 = "#0000FF"
dataSetErrorColor1 = "#0000FF"
dataSetLegendColor1 = "#000000"
dataSetRowTitleColor1 = "#000000"
dataSetBarFillColor2 = "#FF0000"
dataSetBarPatternColor2 = "#FF0000"
dataSetFillColor2 = "#FF0000"
dataSetLineColor2 = "#FF0000"
dataSetBorderColor2 = "#FF0000"
dataSetBackgroundColor2 = "#FF0000"
dataSetErrorColor2 = "#FF0000"
dataSetLegendColor2 = "#000000"
dataSetRowTitleColor2 = "#000000"
dataSetBarFillColor3 = "#00C000"
dataSetBarPatternColor3 = "#00C000"
dataSetFillColor3 = "#00C000"
dataSetLineColor3 = "#00C000"
dataSetBorderColor3 = "#00C000"
dataSetBackgroundColor3 = "#00C000"
dataSetErrorColor3 = "#00C000"
dataSetLegendColor3 = "#000000"
dataSetRowTitleColor3 = "#000000"
dataSetBarFillColor4 = "#AD07E3"
dataSetBarPatternColor4 = "#AD07E3"
dataSetFillColor4 = "#AD07E3"
dataSetLineColor4 = "#AD07E3"
dataSetBorderColor4 = "#AD07E3"
dataSetBackgroundColor4 = "#AD07E3"
dataSetErrorColor4 = "#AD07E3"
dataSetLegendColor4 = "#000000"
dataSetRowTitleColor4 = "#000000"
dataSetBarFillColor5 = "#FF8000"
dataSetBarPatternColor5 = "#FF8000"
dataSetFillColor5 = "#FF8000"
dataSetLineColor5 = "#FF8000"
dataSetBorderColor5 = "#FF8000"
dataSetBackgroundColor5 = "#FF8000"
dataSetErrorColor5 = "#FF8000"
dataSetLegendColor5 = "#000000"
dataSetRowTitleColor5 = "#000000"
dataSetBarFillColor6 = "#000000"
dataSetBarPatternColor6 = "#000000"
dataSetFillColor6 = "#000000"
dataSetLineColor6 = "#000000"
dataSetBorderColor6 = "#000000"
dataSetBackgroundColor6 = "#000000"
dataSetErrorColor6 = "#000000"
dataSetLegendColor6 = "#000000"
dataSetRowTitleColor6 = "#000000"
dataSetBarFillColor7 = "#94641F"
dataSetBarPatternColor7 = "#94641F"
dataSetFillColor7 = "#94641F"
dataSetLineColor7 = "#94641F"
dataSetBorderColor7 = "#94641F"
dataSetBackgroundColor7 = "#94641F"
dataSetErrorColor7 = "#94641F"
dataSetLegendColor7 = "#000000"
dataSetRowTitleColor7 = "#000000"
dataSetBarFillColor8 = "#000080"
dataSetBarPatternColor8 = "#000080"
dataSetFillColor8 = "#000080"
dataSetLineColor8 = "#000080"
dataSetBorderColor8 = "#000080"
dataSetBackgroundColor8 = "#000080"
dataSetErrorColor8 = "#000080"
dataSetLegendColor8 = "#000000"
dataSetRowTitleColor8 = "#000000"
dataSetBarFillColor9 = "#610051"
dataSetBarPatternColor9 = "#610051"
dataSetFillColor9 = "#610051"
dataSetLineColor9 = "#610051"
dataSetBorderColor9 = "#610051"
dataSetBackgroundColor9 = "#610051"
dataSetErrorColor9 = "#610051"
dataSetLegendColor9 = "#000000"
dataSetRowTitleColor9 = "#000000"
dataSetBarFillColor10 = "#A00000"
dataSetBarPatternColor10 = "#A00000"
dataSetFillColor10 = "#A00000"
dataSetLineColor10 = "#A00000"
dataSetBorderColor10 = "#A00000"
dataSetBackgroundColor10 = "#A00000"
dataSetErrorColor10 = "#A00000"
dataSetLegendColor10 = "#000000"
dataSetRowTitleColor10 = "#000000"
dataSetBarFillColor11 = "#005A00"
dataSetBarPatternColor11 = "#005A00"
dataSetFillColor11 = "#005A00"
dataSetLineColor11 = "#005A00"
dataSetBorderColor11 = "#056943"
dataSetBackgroundColor11 = "#005A00"
dataSetErrorColor11 = "#005A00"
dataSetLegendColor11 = "#000000"
dataSetRowTitleColor11 = "#000000"
dataSetBarFillColor12 = "#F2B77C"
dataSetBarPatternColor12 = "#F2B77C"
dataSetFillColor12 = "#F2B77C"
dataSetLineColor12 = "#F2B77C"
dataSetBorderColor12 = "#F2B77C"
dataSetBackgroundColor12 = "#F2B77C"
dataSetErrorColor12 = "#F2B77C"
dataSetLegendColor12 = "#000000"
dataSetRowTitleColor12 = "#000000"
dataSetBarFillColor13 = "#00FF00"
dataSetBarPatternColor13 = "#00FF00"
dataSetFillColor13 = "#00FF00"
dataSetLineColor13 = "#00FF00"
dataSetBorderColor13 = "#00FF00"
dataSetBackgroundColor13 = "#00FF00"
dataSetErrorColor13 = "#00FF00"
dataSetLegendColor13 = "#000000"
dataSetRowTitleColor13 = "#000000"
dataSetBarFillColor14 = "#90BFF9"
dataSetBarPatternColor14 = "#90BFF9"
dataSetFillColor14 = "#90BFF9"
dataSetLineColor14 = "#90BFF9"
dataSetBorderColor14 = "#90BFF9"
dataSetBackgroundColor14 = "#90BFF9"
dataSetErrorColor14 = "#90BFF9"
dataSetLegendColor14 = "#000000"
dataSetRowTitleColor14 = "#000000"
dataSetBarFillColor15 = "#C0C0FF"
dataSetBarPatternColor15 = "#C0C0FF"
dataSetFillColor15 = "#C0C0FF"
dataSetLineColor15 = "#C0C0FF"
dataSetBorderColor15 = "#C0C0FF"
dataSetBackgroundColor15 = "#C0C0FF"
dataSetErrorColor15 = "#C0C0FF"
dataSetLegendColor15 = "#000000"
dataSetRowTitleColor15 = "#000000"
dataSetBarFillColor16 = "#606060"
dataSetBarPatternColor16 = "#606060"
dataSetFillColor16 = "#606060"
dataSetLineColor16 = "#606060"
dataSetBorderColor16 = "#606060"
dataSetBackgroundColor16 = "#606060"
dataSetErrorColor16 = "#606060"
dataSetLegendColor16 = "#000000"
dataSetRowTitleColor16 = "#000000"
dataSetBarFillColor17 = "#FFFF00"
dataSetBarPatternColor17 = "#FFFF00"
dataSetFillColor17 = "#FFFF00"
dataSetLineColor17 = "#FFFF00"
dataSetBorderColor17 = "#FFFF00"
dataSetBackgroundColor17 = "#FFFF00"
dataSetErrorColor17 = "#FFFF00"
dataSetLegendColor17 = "#000000"
dataSetRowTitleColor17 = "#000000"
dataSetBarFillColor18 = "#C06000"
dataSetBarPatternColor18 = "#C06000"
dataSetFillColor18 = "#C06000"
dataSetLineColor18 = "#C06000"
dataSetBorderColor18 = "#C06000"
dataSetBackgroundColor18 = "#C06000"
dataSetErrorColor18 = "#C06000"
dataSetLegendColor18 = "#000000"
dataSetRowTitleColor18 = "#000000"
dataSetBarFillColor19 = "#D4D4D4"
dataSetBarPatternColor19 = "#D4D4D4"
dataSetFillColor19 = "#D4D4D4"
dataSetLineColor19 = "#D4D4D4"
dataSetBorderColor19 = "#D4D4D4"
dataSetBackgroundColor19 = "#D4D4D4"
dataSetErrorColor19 = "#D4D4D4"
dataSetLegendColor19 = "#000000"
dataSetRowTitleColor19 = "#000000"
dataSetBarFillColor20 = "#C0C000"
dataSetBarPatternColor20 = "#C0C000"
dataSetFillColor20 = "#C0C000"
dataSetLineColor20 = "#C0C000"
dataSetBorderColor20 = "#C0C000"
dataSetBackgroundColor20 = "#C0C000"
dataSetErrorColor20 = "#C0C000"
dataSetLegendColor20 = "#000000"
dataSetRowTitleColor20 = "#000000"
