pageBackgroundColor = "#0000FF"
plottingAreaColor = "#FFFFFF"
axisColor = "#FFFFFF"
axisLabelColor = "#FFFFFF"
axisTitleColor = "#FFFFFF"
graphTitleColor = "#FFFFFF"
objectTextColor = "#FFFFFF"
objectFillColor = "#FFFFFF"
objectBorderColor = "#FFFFFF"
objectLinesColor = "#FFFFFF"
objectPatternColor = "#FFFFFF"
embeddedTableBorderColor = "#FFFFFF"
embeddedTableLineUnderTitleColor = "#FFFFFF"
embeddedTableLineNextToRowTitleColor = "#FFFFFF"
embeddedTableTextColor = "#FFFFFF"
embeddedTableGridColor = "#FFFFFF"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#C8DEF9"
dataSetBarPatternColor1 = "#C8DEF9"
dataSetFillColor1 = "#C8DEF9"
dataSetLineColor1 = "#C8DEF9"
dataSetBorderColor1 = "#FFFFFF"
dataSetBackgroundColor1 = "#C8DEF9"
dataSetErrorColor1 = "#FFFFFF"
dataSetLegendColor1 = "#FFFFFF"
dataSetRowTitleColor1 = "#FFFFFF"
dataSetBarFillColor2 = "#90BFF9"
dataSetBarPatternColor2 = "#90BFF9"
dataSetFillColor2 = "#90BFF9"
dataSetLineColor2 = "#90BFF9"
dataSetBorderColor2 = "#FFFFFF"
dataSetBackgroundColor2 = "#90BFF9"
dataSetErrorColor2 = "#FFFFFF"
dataSetLegendColor2 = "#FFFFFF"
dataSetRowTitleColor2 = "#FFFFFF"
dataSetBarFillColor3 = "#B5B5FF"
dataSetBarPatternColor3 = "#B5B5FF"
dataSetFillColor3 = "#B5B5FF"
dataSetLineColor3 = "#FFFFFF"
dataSetBorderColor3 = "#FFFFFF"
dataSetBackgroundColor3 = "#B5B5FF"
dataSetErrorColor3 = "#FFFFFF"
dataSetLegendColor3 = "#FFFFFF"
dataSetRowTitleColor3 = "#FFFFFF"
dataSetBarFillColor4 = "#D4D4D4"
dataSetBarPatternColor4 = "#D4D4D4"
dataSetFillColor4 = "#D4D4D4"
dataSetLineColor4 = "#D4D4D4"
dataSetBorderColor4 = "#FFFFFF"
dataSetBackgroundColor4 = "#D4D4D4"
dataSetErrorColor4 = "#FFFFFF"
dataSetLegendColor4 = "#FFFFFF"
dataSetRowTitleColor4 = "#FFFFFF"
dataSetBarFillColor5 = "#55A0FB"
dataSetBarPatternColor5 = "#55A0FB"
dataSetFillColor5 = "#55A0FB"
dataSetLineColor5 = "#FFFFFF"
dataSetBorderColor5 = "#FFFFFF"
dataSetBackgroundColor5 = "#55A0FB"
dataSetErrorColor5 = "#FFFFFF"
dataSetLegendColor5 = "#FFFFFF"
dataSetRowTitleColor5 = "#FFFFFF"
dataSetBarFillColor6 = "#5757F9"
dataSetBarPatternColor6 = "#5757F9"
dataSetFillColor6 = "#5757F9"
dataSetLineColor6 = "#90BFF9"
dataSetBorderColor6 = "#FFFFFF"
dataSetBackgroundColor6 = "#5757F9"
dataSetErrorColor6 = "#FFFFFF"
dataSetLegendColor6 = "#FFFFFF"
dataSetRowTitleColor6 = "#FFFFFF"
dataSetBarFillColor7 = "#90BFF9"
dataSetBarPatternColor7 = "#90BFF9"
dataSetFillColor7 = "#90BFF9"
dataSetLineColor7 = "#0000FF"
dataSetBorderColor7 = "#FFFFFF"
dataSetBackgroundColor7 = "#90BFF9"
dataSetErrorColor7 = "#FFFFFF"
dataSetLegendColor7 = "#FFFFFF"
dataSetRowTitleColor7 = "#FFFFFF"
dataSetBarFillColor8 = "#8BABD3"
dataSetBarPatternColor8 = "#8BABD3"
dataSetFillColor8 = "#8BABD3"
dataSetLineColor8 = "#C8DEF9"
dataSetBorderColor8 = "#FFFFFF"
dataSetBackgroundColor8 = "#8BABD3"
dataSetErrorColor8 = "#FFFFFF"
dataSetLegendColor8 = "#FFFFFF"
dataSetRowTitleColor8 = "#FFFFFF"
dataSetBarFillColor9 = "#8B90CE"
dataSetBarPatternColor9 = "#8B90CE"
dataSetFillColor9 = "#8B90CE"
dataSetLineColor9 = "#FFFFFF"
dataSetBorderColor9 = "#FFFFFF"
dataSetBackgroundColor9 = "#8B90CE"
dataSetErrorColor9 = "#FFFFFF"
dataSetLegendColor9 = "#FFFFFF"
dataSetRowTitleColor9 = "#FFFFFF"
