pageBackgroundColor = "#D5D8B7"
plottingAreaColor = "#FFFFFF"
axisColor = "#181818"
axisLabelColor = "#181818"
axisTitleColor = "#181818"
graphTitleColor = "#181818"
objectTextColor = "#181818"
objectFillColor = "#FFFFFF"
objectBorderColor = "#383E22"
objectLinesColor = "#383E22"
objectPatternColor = "#383E22"
embeddedTableBorderColor = "#383E22"
embeddedTableLineUnderTitleColor = "#383E22"
embeddedTableLineNextToRowTitleColor = "#383E22"
embeddedTableTextColor = "#181818"
embeddedTableGridColor = "#6F6338"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#4E5B2D"
dataSetBarPatternColor1 = "#4E5B2D"
dataSetFillColor1 = "#4E5B2D"
dataSetLineColor1 = "#383E22"
dataSetBorderColor1 = "#383E22"
dataSetBackgroundColor1 = "#4E5B2D"
dataSetErrorColor1 = "#383E22"
dataSetLegendColor1 = "#383E22"
dataSetRowTitleColor1 = "#383E22"
dataSetBarFillColor2 = "#6F6338"
dataSetBarPatternColor2 = "#6F6338"
dataSetFillColor2 = "#6F6338"
dataSetLineColor2 = "#4C4927"
dataSetBorderColor2 = "#4C4927"
dataSetBackgroundColor2 = "#6F6338"
dataSetErrorColor2 = "#4C4927"
dataSetLegendColor2 = "#4C4927"
dataSetRowTitleColor2 = "#4C4927"
dataSetBarFillColor3 = "#967E55"
dataSetBarPatternColor3 = "#967E55"
dataSetFillColor3 = "#967E55"
dataSetLineColor3 = "#705B46"
dataSetBorderColor3 = "#705B46"
dataSetBackgroundColor3 = "#967E55"
dataSetErrorColor3 = "#705B46"
dataSetLegendColor3 = "#705B46"
dataSetRowTitleColor3 = "#705B46"
dataSetBarFillColor4 = "#6D6058"
dataSetBarPatternColor4 = "#6D6058"
dataSetFillColor4 = "#6D6058"
dataSetLineColor4 = "#463124"
dataSetBorderColor4 = "#463124"
dataSetBackgroundColor4 = "#6D6058"
dataSetErrorColor4 = "#463124"
dataSetLegendColor4 = "#463124"
dataSetRowTitleColor4 = "#463124"
dataSetBarFillColor5 = "#4E5246"
dataSetBarPatternColor5 = "#4E5246"
dataSetFillColor5 = "#4E5246"
dataSetLineColor5 = "#242620"
dataSetBorderColor5 = "#242620"
dataSetBackgroundColor5 = "#4E5246"
dataSetErrorColor5 = "#242620"
dataSetLegendColor5 = "#242620"
dataSetRowTitleColor5 = "#242620"
dataSetBarFillColor6 = "#758942"
dataSetBarPatternColor6 = "#758942"
dataSetFillColor6 = "#758942"
dataSetLineColor6 = "#4E5B2D"
dataSetBorderColor6 = "#4E5B2D"
dataSetBackgroundColor6 = "#758942"
dataSetErrorColor6 = "#4E5B2D"
dataSetLegendColor6 = "#4E5B2D"
dataSetRowTitleColor6 = "#4E5B2D"
dataSetBarFillColor7 = "#93824A"
dataSetBarPatternColor7 = "#93824A"
dataSetFillColor7 = "#93824A"
dataSetLineColor7 = "#6F6338"
dataSetBorderColor7 = "#6F6338"
dataSetBackgroundColor7 = "#93824A"
dataSetErrorColor7 = "#6F6338"
dataSetLegendColor7 = "#6F6338"
dataSetRowTitleColor7 = "#6F6338"
dataSetBarFillColor8 = "#8A744E"
dataSetBarPatternColor8 = "#8A744E"
dataSetFillColor8 = "#8A744E"
dataSetLineColor8 = "#713C34"
dataSetBorderColor8 = "#713C34"
dataSetBackgroundColor8 = "#8A744E"
dataSetErrorColor8 = "#713C34"
dataSetLegendColor8 = "#713C34"
dataSetRowTitleColor8 = "#713C34"
dataSetBarFillColor9 = "#827268"
dataSetBarPatternColor9 = "#827268"
dataSetFillColor9 = "#827268"
dataSetLineColor9 = "#534943"
dataSetBorderColor9 = "#534943"
dataSetBackgroundColor9 = "#827268"
dataSetErrorColor9 = "#534943"
dataSetLegendColor9 = "#534943"
dataSetRowTitleColor9 = "#534943"
dataSetBarFillColor10 = "#33362E"
dataSetBarPatternColor10 = "#33362E"
dataSetFillColor10 = "#33362E"
dataSetLineColor10 = "#33362E"
dataSetBorderColor10 = "#33362E"
dataSetBackgroundColor10 = "#33362E"
dataSetErrorColor10 = "#33362E"
dataSetLegendColor10 = "#33362E"
dataSetRowTitleColor10 = "#33362E"
