pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#008000"
axisLabelColor = "#008000"
axisTitleColor = "#008000"
graphTitleColor = "#008000"
objectTextColor = "#008000"
objectFillColor = "#FFFFFF"
objectBorderColor = "#008000"
objectLinesColor = "#008000"
objectPatternColor = "#008000"
embeddedTableBorderColor = "#000080"
embeddedTableLineUnderTitleColor = "#000080"
embeddedTableLineNextToRowTitleColor = "#000080"
embeddedTableTextColor = "#000080"
embeddedTableGridColor = "#000080"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#005A00"
dataSetBarPatternColor1 = "#005A00"
dataSetFillColor1 = "#005A00"
dataSetLineColor1 = "#005A00"
dataSetBorderColor1 = "#005A00"
dataSetBackgroundColor1 = "#005A00"
dataSetErrorColor1 = "#005A00"
dataSetLegendColor1 = "#005A00"
dataSetRowTitleColor1 = "#005A00"
dataSetBarFillColor2 = "#099963"
dataSetBarPatternColor2 = "#099963"
dataSetFillColor2 = "#099963"
dataSetLineColor2 = "#099963"
dataSetBorderColor2 = "#099963"
dataSetBackgroundColor2 = "#099963"
dataSetErrorColor2 = "#099963"
dataSetLegendColor2 = "#005A00"
dataSetRowTitleColor2 = "#005A00"
dataSetBarFillColor3 = "#00C000"
dataSetBarPatternColor3 = "#00C000"
dataSetFillColor3 = "#00C000"
dataSetLineColor3 = "#00C000"
dataSetBorderColor3 = "#00C000"
dataSetBackgroundColor3 = "#00C000"
dataSetErrorColor3 = "#00C000"
dataSetLegendColor3 = "#005A00"
dataSetRowTitleColor3 = "#005A00"
dataSetBarFillColor4 = "#008000"
dataSetBarPatternColor4 = "#008000"
dataSetFillColor4 = "#008000"
dataSetLineColor4 = "#008000"
dataSetBorderColor4 = "#008000"
dataSetBackgroundColor4 = "#008000"
dataSetErrorColor4 = "#008000"
dataSetLegendColor4 = "#005A00"
dataSetRowTitleColor4 = "#005A00"
dataSetBarFillColor5 = "#05BE78"
dataSetBarPatternColor5 = "#05BE78"
dataSetFillColor5 = "#05BE78"
dataSetLineColor5 = "#05BE78"
dataSetBorderColor5 = "#05BE78"
dataSetBackgroundColor5 = "#05BE78"
dataSetErrorColor5 = "#05BE78"
dataSetLegendColor5 = "#005A00"
dataSetRowTitleColor5 = "#005A00"
dataSetBarFillColor6 = "#099963"
dataSetBarPatternColor6 = "#099963"
dataSetFillColor6 = "#099963"
dataSetLineColor6 = "#099963"
dataSetBorderColor6 = "#099963"
dataSetBackgroundColor6 = "#099963"
dataSetErrorColor6 = "#099963"
dataSetLegendColor6 = "#005A00"
dataSetRowTitleColor6 = "#005A00"
dataSetBarFillColor7 = "#ADDEAD"
dataSetBarPatternColor7 = "#ADDEAD"
dataSetFillColor7 = "#ADDEAD"
dataSetLineColor7 = "#ADDEAD"
dataSetBorderColor7 = "#ADDEAD"
dataSetBackgroundColor7 = "#ADDEAD"
dataSetErrorColor7 = "#ADDEAD"
dataSetLegendColor7 = "#005A00"
dataSetRowTitleColor7 = "#005A00"
dataSetBarFillColor8 = "#0F99B2"
dataSetBarPatternColor8 = "#0F99B2"
dataSetFillColor8 = "#0F99B2"
dataSetLineColor8 = "#0F99B2"
dataSetBorderColor8 = "#0F99B2"
dataSetBackgroundColor8 = "#0F99B2"
dataSetErrorColor8 = "#0F99B2"
dataSetLegendColor8 = "#005A00"
dataSetRowTitleColor8 = "#005A00"
dataSetBarFillColor9 = "#0A9444"
dataSetBarPatternColor9 = "#0A9444"
dataSetFillColor9 = "#0A9444"
dataSetLineColor9 = "#0A9444"
dataSetBorderColor9 = "#0A9444"
dataSetBackgroundColor9 = "#0A9444"
dataSetErrorColor9 = "#0A9444"
dataSetLegendColor9 = "#005A00"
dataSetRowTitleColor9 = "#005A00"
