pageBackgroundColor = "#EAFEFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#000000"
axisLabelColor = "#000000"
axisTitleColor = "#000000"
graphTitleColor = "#000000"
objectTextColor = "#000000"
objectFillColor = "#FFFFFF"
objectBorderColor = "#336666"
objectLinesColor = "#20B2AA"
objectPatternColor = "#20B2AA"
embeddedTableBorderColor = "#20B2AA"
embeddedTableLineUnderTitleColor = "#20B2AA"
embeddedTableLineNextToRowTitleColor = "#20B2AA"
embeddedTableTextColor = "#336666"
embeddedTableGridColor = "#20B2AA"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#9DF8FF"
dataSetBarPatternColor1 = "#9DF8FF"
dataSetFillColor1 = "#9DF8FF"
dataSetLineColor1 = "#9DF8FF"
dataSetBorderColor1 = "#336666"
dataSetBackgroundColor1 = "#9DF8FF"
dataSetErrorColor1 = "#336666"
dataSetLegendColor1 = "#336666"
dataSetRowTitleColor1 = "#000000"
dataSetBarFillColor2 = "#20B2AA"
dataSetBarPatternColor2 = "#20B2AA"
dataSetFillColor2 = "#20B2AA"
dataSetLineColor2 = "#20B2AA"
dataSetBorderColor2 = "#20B2AA"
dataSetBackgroundColor2 = "#20B2AA"
dataSetErrorColor2 = "#20B2AA"
dataSetLegendColor2 = "#336666"
dataSetRowTitleColor2 = "#000000"
dataSetBarFillColor3 = "#99CCCC"
dataSetBarPatternColor3 = "#99CCCC"
dataSetFillColor3 = "#99CCCC"
dataSetLineColor3 = "#99CCCC"
dataSetBorderColor3 = "#99CCCC"
dataSetBackgroundColor3 = "#99CCCC"
dataSetErrorColor3 = "#99CCCC"
dataSetLegendColor3 = "#336666"
dataSetRowTitleColor3 = "#000000"
dataSetBarFillColor4 = "#9DF8FF"
dataSetBarPatternColor4 = "#9DF8FF"
dataSetFillColor4 = "#9DF8FF"
dataSetLineColor4 = "#9DF8FF"
dataSetBorderColor4 = "#20B2AA"
dataSetBackgroundColor4 = "#9DF8FF"
dataSetErrorColor4 = "#20B2AA"
dataSetLegendColor4 = "#336666"
dataSetRowTitleColor4 = "#000000"
dataSetBarFillColor5 = "#336666"
dataSetBarPatternColor5 = "#336666"
dataSetFillColor5 = "#336666"
dataSetLineColor5 = "#336666"
dataSetBorderColor5 = "#000000"
dataSetBackgroundColor5 = "#336666"
dataSetErrorColor5 = "#336666"
dataSetLegendColor5 = "#336666"
dataSetRowTitleColor5 = "#000000"
dataSetBarFillColor6 = "#20B2AA"
dataSetBarPatternColor6 = "#20B2AA"
dataSetFillColor6 = "#20B2AA"
dataSetLineColor6 = "#20B2AA"
dataSetBorderColor6 = "#20B2AA"
dataSetBackgroundColor6 = "#20B2AA"
dataSetErrorColor6 = "#20B2AA"
dataSetLegendColor6 = "#336666"
dataSetRowTitleColor6 = "#000000"
dataSetBarFillColor7 = "#99CCCC"
dataSetBarPatternColor7 = "#99CCCC"
dataSetFillColor7 = "#99CCCC"
dataSetLineColor7 = "#99CCCC"
dataSetBorderColor7 = "#336666"
dataSetBackgroundColor7 = "#99CCCC"
dataSetErrorColor7 = "#336666"
dataSetLegendColor7 = "#336666"
dataSetRowTitleColor7 = "#000000"
dataSetBarFillColor8 = "#000000"
dataSetBarPatternColor8 = "#000000"
dataSetFillColor8 = "#000000"
dataSetLineColor8 = "#000000"
dataSetBorderColor8 = "#000000"
dataSetBackgroundColor8 = "#000000"
dataSetErrorColor8 = "#000000"
dataSetLegendColor8 = "#336666"
dataSetRowTitleColor8 = "#000000"
dataSetBarFillColor9 = "#336666"
dataSetBarPatternColor9 = "#336666"
dataSetFillColor9 = "#336666"
dataSetLineColor9 = "#336666"
dataSetBorderColor9 = "#336666"
dataSetBackgroundColor9 = "#336666"
dataSetErrorColor9 = "#336666"
dataSetLegendColor9 = "#336666"
dataSetRowTitleColor9 = "#000000"
