pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#FF9900"
axisLabelColor = "#CD3807"
axisTitleColor = "#CD3807"
graphTitleColor = "#CD3807"
objectTextColor = "#CD3807"
objectFillColor = "#FFFFFF"
objectBorderColor = "#CD3807"
objectLinesColor = "#CD3807"
objectPatternColor = "#CD3807"
embeddedTableBorderColor = "#FF9900"
embeddedTableLineUnderTitleColor = "#FF9900"
embeddedTableLineNextToRowTitleColor = "#FF9900"
embeddedTableTextColor = "#CD3807"
embeddedTableGridColor = "#FF9900"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#FFCC00"
dataSetBarPatternColor1 = "#FFCC00"
dataSetFillColor1 = "#FFCC00"
dataSetLineColor1 = "#FFCC00"
dataSetBorderColor1 = "#FFCC00"
dataSetBackgroundColor1 = "#FFCC00"
dataSetErrorColor1 = "#FFCC00"
dataSetLegendColor1 = "#CC0000"
dataSetRowTitleColor1 = "#000000"
dataSetBarFillColor2 = "#FF9900"
dataSetBarPatternColor2 = "#FF9900"
dataSetFillColor2 = "#FF9900"
dataSetLineColor2 = "#FF9900"
dataSetBorderColor2 = "#FF9900"
dataSetBackgroundColor2 = "#FF9900"
dataSetErrorColor2 = "#FF9900"
dataSetLegendColor2 = "#FF9900"
dataSetRowTitleColor2 = "#000000"
dataSetBarFillColor3 = "#CD3807"
dataSetBarPatternColor3 = "#CD3807"
dataSetFillColor3 = "#CD3807"
dataSetLineColor3 = "#CD3807"
dataSetBorderColor3 = "#CD3807"
dataSetBackgroundColor3 = "#CD3807"
dataSetErrorColor3 = "#CD3807"
dataSetLegendColor3 = "#CD3807"
dataSetRowTitleColor3 = "#000000"
dataSetBarFillColor4 = "#FFAD21"
dataSetBarPatternColor4 = "#FFAD21"
dataSetFillColor4 = "#FFAD21"
dataSetLineColor4 = "#FFAD21"
dataSetBorderColor4 = "#FFAD21"
dataSetBackgroundColor4 = "#FFAD21"
dataSetErrorColor4 = "#FFAD21"
dataSetLegendColor4 = "#FFAD21"
dataSetRowTitleColor4 = "#000000"
dataSetBarFillColor5 = "#FFFF33"
dataSetBarPatternColor5 = "#FFFF33"
dataSetFillColor5 = "#FFFF33"
dataSetLineColor5 = "#FFFF33"
dataSetBorderColor5 = "#FFAD21"
dataSetBackgroundColor5 = "#FFFF33"
dataSetErrorColor5 = "#FFAD21"
dataSetLegendColor5 = "#CC0000"
dataSetRowTitleColor5 = "#000000"
dataSetBarFillColor6 = "#F40000"
dataSetBarPatternColor6 = "#F40000"
dataSetFillColor6 = "#F40000"
dataSetLineColor6 = "#F40000"
dataSetBorderColor6 = "#F40000"
dataSetBackgroundColor6 = "#F40000"
dataSetErrorColor6 = "#F40000"
dataSetLegendColor6 = "#FF9900"
dataSetRowTitleColor6 = "#000000"
dataSetBarFillColor7 = "#FF9900"
dataSetBarPatternColor7 = "#FF9900"
dataSetFillColor7 = "#FF9900"
dataSetLineColor7 = "#FF9900"
dataSetBorderColor7 = "#FF9900"
dataSetBackgroundColor7 = "#FF9900"
dataSetErrorColor7 = "#FF9900"
dataSetLegendColor7 = "#CC0000"
dataSetRowTitleColor7 = "#000000"
dataSetBarFillColor8 = "#FFCC00"
dataSetBarPatternColor8 = "#FFCC00"
dataSetFillColor8 = "#FFCC00"
dataSetLineColor8 = "#FFCC00"
dataSetBorderColor8 = "#FFCC00"
dataSetBackgroundColor8 = "#FFCC00"
dataSetErrorColor8 = "#FFCC00"
dataSetLegendColor8 = "#FF9900"
dataSetRowTitleColor8 = "#000000"
dataSetBarFillColor9 = "#FFFF33"
dataSetBarPatternColor9 = "#FFFF33"
dataSetFillColor9 = "#FFFF33"
dataSetLineColor9 = "#FFFF33"
dataSetBorderColor9 = "#FFCC00"
dataSetBackgroundColor9 = "#FFFF33"
dataSetErrorColor9 = "#FFCC00"
dataSetLegendColor9 = "#CC0000"
dataSetRowTitleColor9 = "#000000"
