pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#000000"
axisLabelColor = "#000000"
axisTitleColor = "#000000"
graphTitleColor = "#000000"
objectTextColor = "#000000"
objectFillColor = "#FFFFFF"
objectBorderColor = "#000000"
objectLinesColor = "#000000"
objectPatternColor = "#000000"
embeddedTableBorderColor = "#000000"
embeddedTableLineUnderTitleColor = "#000000"
embeddedTableLineNextToRowTitleColor = "#000000"
embeddedTableTextColor = "#000000"
embeddedTableGridColor = "#000000"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#7CA0D4"
dataSetBarPatternColor1 = "#7CA0D4"
dataSetFillColor1 = "#7CA0D4"
dataSetLineColor1 = "#7CA0D4"
dataSetBorderColor1 = "#285291"
dataSetBackgroundColor1 = "#7CA0D4"
dataSetErrorColor1 = "#285291"
dataSetLegendColor1 = "#000000"
dataSetRowTitleColor1 = "#000000"
dataSetBarFillColor2 = "#A48AD3"
dataSetBarPatternColor2 = "#A48AD3"
dataSetFillColor2 = "#A48AD3"
dataSetLineColor2 = "#A48AD3"
dataSetBorderColor2 = "#4F2B8E"
dataSetBackgroundColor2 = "#A48AD3"
dataSetErrorColor2 = "#4F2B8E"
dataSetLegendColor2 = "#000000"
dataSetRowTitleColor2 = "#000000"
dataSetBarFillColor3 = "#E995EB"
dataSetBarPatternColor3 = "#E995EB"
dataSetFillColor3 = "#E995EB"
dataSetLineColor3 = "#E995EB"
dataSetBorderColor3 = "#91188E"
dataSetBackgroundColor3 = "#E995EB"
dataSetErrorColor3 = "#91188E"
dataSetLegendColor3 = "#000000"
dataSetRowTitleColor3 = "#000000"
dataSetBarFillColor4 = "#BADE86"
dataSetBarPatternColor4 = "#BADE86"
dataSetFillColor4 = "#BADE86"
dataSetLineColor4 = "#BADE86"
dataSetBorderColor4 = "#539027"
dataSetBackgroundColor4 = "#BADE86"
dataSetErrorColor4 = "#539027"
dataSetLegendColor4 = "#000000"
dataSetRowTitleColor4 = "#000000"
dataSetBarFillColor5 = "#2B8AAE"
dataSetBarPatternColor5 = "#2B8AAE"
dataSetFillColor5 = "#2B8AAE"
dataSetLineColor5 = "#2B8AAE"
dataSetBorderColor5 = "#0D405B"
dataSetBackgroundColor5 = "#2B8AAE"
dataSetErrorColor5 = "#0D405B"
dataSetLegendColor5 = "#000000"
dataSetRowTitleColor5 = "#000000"
dataSetBarFillColor6 = "#624894"
dataSetBarPatternColor6 = "#624894"
dataSetFillColor6 = "#624894"
dataSetLineColor6 = "#624894"
dataSetBorderColor6 = "#34274D"
dataSetBackgroundColor6 = "#624894"
dataSetErrorColor6 = "#34274D"
dataSetLegendColor6 = "#000000"
dataSetRowTitleColor6 = "#000000"
dataSetBarFillColor7 = "#DE757B"
dataSetBarPatternColor7 = "#DE757B"
dataSetFillColor7 = "#DE757B"
dataSetLineColor7 = "#DE757B"
dataSetBorderColor7 = "#91181D"
dataSetBackgroundColor7 = "#DE757B"
dataSetErrorColor7 = "#91181D"
dataSetLegendColor7 = "#000000"
dataSetRowTitleColor7 = "#000000"
dataSetBarFillColor8 = "#8BA56F"
dataSetBarPatternColor8 = "#8BA56F"
dataSetFillColor8 = "#8BA56F"
dataSetLineColor8 = "#8BA56F"
dataSetBorderColor8 = "#2C3324"
dataSetBackgroundColor8 = "#8BA56F"
dataSetErrorColor8 = "#2C3324"
dataSetLegendColor8 = "#000000"
dataSetRowTitleColor8 = "#000000"
dataSetBarFillColor9 = "#073F80"
dataSetBarPatternColor9 = "#073F80"
dataSetFillColor9 = "#073F80"
dataSetLineColor9 = "#073F80"
dataSetBorderColor9 = "#022240"
dataSetBackgroundColor9 = "#073F80"
dataSetErrorColor9 = "#022240"
dataSetLegendColor9 = "#000000"
dataSetRowTitleColor9 = "#000000"
dataSetBarFillColor10 = "#40007F"
dataSetBarPatternColor10 = "#40007F"
dataSetFillColor10 = "#40007F"
dataSetLineColor10 = "#40007F"
dataSetBorderColor10 = "#21063F"
dataSetBackgroundColor10 = "#40007F"
dataSetErrorColor10 = "#21063F"
dataSetLegendColor10 = "#000000"
dataSetRowTitleColor10 = "#000000"
dataSetBarFillColor11 = "#80003F"
dataSetBarPatternColor11 = "#80003F"
dataSetFillColor11 = "#80003F"
dataSetLineColor11 = "#80003F"
dataSetBorderColor11 = "#3D0620"
dataSetBackgroundColor11 = "#80003F"
dataSetErrorColor11 = "#3D0620"
dataSetLegendColor11 = "#000000"
dataSetRowTitleColor11 = "#000000"
dataSetBarFillColor12 = "#0A522A"
dataSetBarPatternColor12 = "#0A522A"
dataSetFillColor12 = "#0A522A"
dataSetLineColor12 = "#0A522A"
dataSetBorderColor12 = "#022013"
dataSetBackgroundColor12 = "#0A522A"
dataSetErrorColor12 = "#022013"
dataSetLegendColor12 = "#000000"
dataSetRowTitleColor12 = "#000000"
