pageBackgroundColor = "#DFFBA7"
plottingAreaColor = "#FFFFFF"
axisColor = "#421814"
axisLabelColor = "#421814"
axisTitleColor = "#421814"
graphTitleColor = "#421814"
objectTextColor = "#181818"
objectFillColor = "#FFFFFF"
objectBorderColor = "#421814"
objectLinesColor = "#421814"
objectPatternColor = "#421814"
embeddedTableBorderColor = "#421814"
embeddedTableLineUnderTitleColor = "#421814"
embeddedTableLineNextToRowTitleColor = "#421814"
embeddedTableTextColor = "#181818"
embeddedTableGridColor = "#845852"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#845852"
dataSetBarPatternColor1 = "#845852"
dataSetFillColor1 = "#845852"
dataSetLineColor1 = "#512305"
dataSetBorderColor1 = "#512305"
dataSetBackgroundColor1 = "#845852"
dataSetErrorColor1 = "#512305"
dataSetLegendColor1 = "#512305"
dataSetRowTitleColor1 = "#73130F"
dataSetBarFillColor2 = "#993D38"
dataSetBarPatternColor2 = "#993D38"
dataSetFillColor2 = "#993D38"
dataSetLineColor2 = "#73130F"
dataSetBorderColor2 = "#73130F"
dataSetBackgroundColor2 = "#993D38"
dataSetErrorColor2 = "#73130F"
dataSetLegendColor2 = "#73130F"
dataSetRowTitleColor2 = "#512305"
dataSetBarFillColor3 = "#E98440"
dataSetBarPatternColor3 = "#E98440"
dataSetFillColor3 = "#E98440"
dataSetLineColor3 = "#AF4B1B"
dataSetBorderColor3 = "#AF4B1B"
dataSetBackgroundColor3 = "#E98440"
dataSetErrorColor3 = "#AF4B1B"
dataSetLegendColor3 = "#AF4B1B"
dataSetRowTitleColor3 = "#AF4B1B"
dataSetBarFillColor4 = "#5A5448"
dataSetBarPatternColor4 = "#5A5448"
dataSetFillColor4 = "#5A5448"
dataSetLineColor4 = "#181818"
dataSetBorderColor4 = "#181818"
dataSetBackgroundColor4 = "#5A5448"
dataSetErrorColor4 = "#181818"
dataSetLegendColor4 = "#181818"
dataSetRowTitleColor4 = "#181818"
dataSetBarFillColor5 = "#818C5A"
dataSetBarPatternColor5 = "#818C5A"
dataSetFillColor5 = "#818C5A"
dataSetLineColor5 = "#435D14"
dataSetBorderColor5 = "#435D14"
dataSetBackgroundColor5 = "#818C5A"
dataSetErrorColor5 = "#435D14"
dataSetLegendColor5 = "#435D14"
dataSetRowTitleColor5 = "#435D14"
dataSetBarFillColor6 = "#E25B54"
dataSetBarPatternColor6 = "#E25B54"
dataSetFillColor6 = "#E25B54"
dataSetLineColor6 = "#993D38"
dataSetBorderColor6 = "#993D38"
dataSetBackgroundColor6 = "#E25B54"
dataSetErrorColor6 = "#993D38"
dataSetLegendColor6 = "#993D38"
dataSetRowTitleColor6 = "#993D38"
dataSetBarFillColor7 = "#CF7F4D"
dataSetBarPatternColor7 = "#CF7F4D"
dataSetFillColor7 = "#CF7F4D"
dataSetLineColor7 = "#845852"
dataSetBorderColor7 = "#845852"
dataSetBackgroundColor7 = "#CF7F4D"
dataSetErrorColor7 = "#845852"
dataSetLegendColor7 = "#845852"
dataSetRowTitleColor7 = "#845852"
dataSetBarFillColor8 = "#FEC3A0"
dataSetBarPatternColor8 = "#FEC3A0"
dataSetFillColor8 = "#FEC3A0"
dataSetLineColor8 = "#E98440"
dataSetBorderColor8 = "#E98440"
dataSetBackgroundColor8 = "#FEC3A0"
dataSetErrorColor8 = "#E98440"
dataSetLegendColor8 = "#E98440"
dataSetRowTitleColor8 = "#E98440"
dataSetBarFillColor9 = "#848484"
dataSetBarPatternColor9 = "#848484"
dataSetFillColor9 = "#848484"
dataSetLineColor9 = "#5A5448"
dataSetBorderColor9 = "#5A5448"
dataSetBackgroundColor9 = "#848484"
dataSetErrorColor9 = "#5A5448"
dataSetLegendColor9 = "#5A5448"
dataSetRowTitleColor9 = "#5A5448"
dataSetBarFillColor10 = "#90C82B"
dataSetBarPatternColor10 = "#90C82B"
dataSetFillColor10 = "#90C82B"
dataSetLineColor10 = "#818C5A"
dataSetBorderColor10 = "#818C5A"
dataSetBackgroundColor10 = "#90C82B"
dataSetErrorColor10 = "#818C5A"
dataSetLegendColor10 = "#818C5A"
dataSetRowTitleColor10 = "#818C5A"
