pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#000000"
axisLabelColor = "#000000"
axisTitleColor = "#000000"
graphTitleColor = "#000000"
objectTextColor = "#000000"
objectFillColor = "#FFFFFF"
objectBorderColor = "#000000"
objectLinesColor = "#000000"
objectPatternColor = "#000000"
embeddedTableBorderColor = "#000000"
embeddedTableLineUnderTitleColor = "#000000"
embeddedTableLineNextToRowTitleColor = "#000000"
embeddedTableTextColor = "#000000"
embeddedTableGridColor = "#000000"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#000004"
dataSetBarPatternColor1 = "#000004"
dataSetFillColor1 = "#000004"
dataSetLineColor1 = "#000004"
dataSetBorderColor1 = "#000000"
dataSetBackgroundColor1 = "#000004"
dataSetErrorColor1 = "#000000"
dataSetLegendColor1 = "#000000"
dataSetRowTitleColor1 = "#000004"
dataSetBarFillColor2 = "#420A68"
dataSetBarPatternColor2 = "#420A68"
dataSetFillColor2 = "#420A68"
dataSetLineColor2 = "#420A68"
dataSetBorderColor2 = "#000000"
dataSetBackgroundColor2 = "#420A68"
dataSetErrorColor2 = "#000000"
dataSetLegendColor2 = "#000000"
dataSetRowTitleColor2 = "#420A68"
dataSetBarFillColor3 = "#932667"
dataSetBarPatternColor3 = "#932667"
dataSetFillColor3 = "#932667"
dataSetLineColor3 = "#932667"
dataSetBorderColor3 = "#000000"
dataSetBackgroundColor3 = "#932667"
dataSetErrorColor3 = "#000000"
dataSetLegendColor3 = "#000000"
dataSetRowTitleColor3 = "#932667"
dataSetBarFillColor4 = "#DD513A"
dataSetBarPatternColor4 = "#DD513A"
dataSetFillColor4 = "#DD513A"
dataSetLineColor4 = "#DD513A"
dataSetBorderColor4 = "#000000"
dataSetBackgroundColor4 = "#DD513A"
dataSetErrorColor4 = "#000000"
dataSetLegendColor4 = "#000000"
dataSetRowTitleColor4 = "#DD513A"
dataSetBarFillColor5 = "#FCA50A"
dataSetBarPatternColor5 = "#FCA50A"
dataSetFillColor5 = "#FCA50A"
dataSetLineColor5 = "#FCA50A"
dataSetBorderColor5 = "#000000"
dataSetBackgroundColor5 = "#FCA50A"
dataSetErrorColor5 = "#000000"
dataSetLegendColor5 = "#000000"
dataSetRowTitleColor5 = "#FCA50A"
dataSetBarFillColor6 = "#FCFFA4"
dataSetBarPatternColor6 = "#FCFFA4"
dataSetFillColor6 = "#FCFFA4"
dataSetLineColor6 = "#FCFFA4"
dataSetBorderColor6 = "#000000"
dataSetBackgroundColor6 = "#FCFFA4"
dataSetErrorColor6 = "#000000"
dataSetLegendColor6 = "#000000"
dataSetRowTitleColor6 = "#FCFFA4"
