pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#000000"
axisLabelColor = "#000000"
axisTitleColor = "#000000"
graphTitleColor = "#000000"
objectTextColor = "#000000"
objectFillColor = "#FFFFFF"
objectBorderColor = "#000000"
objectLinesColor = "#000000"
objectPatternColor = "#000000"
embeddedTableBorderColor = "#000000"
embeddedTableLineUnderTitleColor = "#000000"
embeddedTableLineNextToRowTitleColor = "#000000"
embeddedTableTextColor = "#000000"
embeddedTableGridColor = "#000000"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#000004"
dataSetBarPatternColor1 = "#000004"
dataSetFillColor1 = "#000004"
dataSetLineColor1 = "#000004"
dataSetBorderColor1 = "#000000"
dataSetBackgroundColor1 = "#000004"
dataSetErrorColor1 = "#000000"
dataSetLegendColor1 = "#000000"
dataSetRowTitleColor1 = "#000004"
dataSetBarFillColor2 = "#3B0F70"
dataSetBarPatternColor2 = "#3B0F70"
dataSetFillColor2 = "#3B0F70"
dataSetLineColor2 = "#3B0F70"
dataSetBorderColor2 = "#000000"
dataSetBackgroundColor2 = "#3B0F70"
dataSetErrorColor2 = "#000000"
dataSetLegendColor2 = "#000000"
dataSetRowTitleColor2 = "#3B0F70"
dataSetBarFillColor3 = "#8C2981"
dataSetBarPatternColor3 = "#8C2981"
dataSetFillColor3 = "#8C2981"
dataSetLineColor3 = "#8C2981"
dataSetBorderColor3 = "#000000"
dataSetBackgroundColor3 = "#8C2981"
dataSetErrorColor3 = "#000000"
dataSetLegendColor3 = "#000000"
dataSetRowTitleColor3 = "#8C2981"
dataSetBarFillColor4 = "#DE4968"
dataSetBarPatternColor4 = "#DE4968"
dataSetFillColor4 = "#DE4968"
dataSetLineColor4 = "#DE4968"
dataSetBorderColor4 = "#000000"
dataSetBackgroundColor4 = "#DE4968"
dataSetErrorColor4 = "#000000"
dataSetLegendColor4 = "#000000"
dataSetRowTitleColor4 = "#DE4968"
dataSetBarFillColor5 = "#FE9F6D"
dataSetBarPatternColor5 = "#FE9F6D"
dataSetFillColor5 = "#FE9F6D"
dataSetLineColor5 = "#FE9F6D"
dataSetBorderColor5 = "#000000"
dataSetBackgroundColor5 = "#FE9F6D"
dataSetErrorColor5 = "#000000"
dataSetLegendColor5 = "#000000"
dataSetRowTitleColor5 = "#FE9F6D"
dataSetBarFillColor6 = "#FCFDBF"
dataSetBarPatternColor6 = "#FCFDBF"
dataSetFillColor6 = "#FCFDBF"
dataSetLineColor6 = "#FCFDBF"
dataSetBorderColor6 = "#000000"
dataSetBackgroundColor6 = "#FCFDBF"
dataSetErrorColor6 = "#000000"
dataSetLegendColor6 = "#000000"
dataSetRowTitleColor6 = "#FCFDBF"
