pageBackgroundColor = "#FFFFE0"
plottingAreaColor = "#FFFFFF"
axisColor = "#94641F"
axisLabelColor = "#94641F"
axisTitleColor = "#94641F"
graphTitleColor = "#94641F"
objectTextColor = "#27273D"
objectFillColor = "#FFFFFF"
objectBorderColor = "#C06000"
objectLinesColor = "#8B90CE"
objectPatternColor = "#C0C000"
embeddedTableBorderColor = "#A00000"
embeddedTableLineUnderTitleColor = "#A00000"
embeddedTableLineNextToRowTitleColor = "#A00000"
embeddedTableTextColor = "#5B63B9"
embeddedTableGridColor = "#A00000"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#C0B57B"
dataSetBarPatternColor1 = "#C0B57B"
dataSetFillColor1 = "#C0B57B"
dataSetLineColor1 = "#C0B57B"
dataSetBorderColor1 = "#C0B57B"
dataSetBackgroundColor1 = "#C0B57B"
dataSetErrorColor1 = "#C0B57B"
dataSetLegendColor1 = "#94641F"
dataSetRowTitleColor1 = "#94641F"
dataSetBarFillColor2 = "#808000"
dataSetBarPatternColor2 = "#808000"
dataSetFillColor2 = "#808000"
dataSetLineColor2 = "#8C7D37"
dataSetBorderColor2 = "#808000"
dataSetBackgroundColor2 = "#808000"
dataSetErrorColor2 = "#808000"
dataSetLegendColor2 = "#94641F"
dataSetRowTitleColor2 = "#94641F"
dataSetBarFillColor3 = "#C0C000"
dataSetBarPatternColor3 = "#C0C000"
dataSetFillColor3 = "#C0C000"
dataSetLineColor3 = "#C0C000"
dataSetBorderColor3 = "#C0C000"
dataSetBackgroundColor3 = "#C0C000"
dataSetErrorColor3 = "#C0C000"
dataSetLegendColor3 = "#94641F"
dataSetRowTitleColor3 = "#94641F"
dataSetBarFillColor4 = "#C5944E"
dataSetBarPatternColor4 = "#C5944E"
dataSetFillColor4 = "#C5944E"
dataSetLineColor4 = "#C5944E"
dataSetBorderColor4 = "#8C7D37"
dataSetBackgroundColor4 = "#C5944E"
dataSetErrorColor4 = "#C5944E"
dataSetLegendColor4 = "#94641F"
dataSetRowTitleColor4 = "#94641F"
dataSetBarFillColor5 = "#918751"
dataSetBarPatternColor5 = "#918751"
dataSetFillColor5 = "#918751"
dataSetLineColor5 = "#918751"
dataSetBorderColor5 = "#918751"
dataSetBackgroundColor5 = "#918751"
dataSetErrorColor5 = "#918751"
dataSetLegendColor5 = "#94641F"
dataSetRowTitleColor5 = "#94641F"
dataSetBarFillColor6 = "#FFC080"
dataSetBarPatternColor6 = "#FFC080"
dataSetFillColor6 = "#FFC080"
dataSetLineColor6 = "#FFC080"
dataSetBorderColor6 = "#808000"
dataSetBackgroundColor6 = "#FFC080"
dataSetErrorColor6 = "#FFC080"
dataSetLegendColor6 = "#94641F"
dataSetRowTitleColor6 = "#94641F"
dataSetBarFillColor7 = "#C0B57B"
dataSetBarPatternColor7 = "#C0B57B"
dataSetFillColor7 = "#C0B57B"
dataSetLineColor7 = "#C0B57B"
dataSetBorderColor7 = "#C0B57B"
dataSetBackgroundColor7 = "#C0B57B"
dataSetErrorColor7 = "#C0B57B"
dataSetLegendColor7 = "#94641F"
dataSetRowTitleColor7 = "#94641F"
dataSetBarFillColor8 = "#808000"
dataSetBarPatternColor8 = "#808000"
dataSetFillColor8 = "#808000"
dataSetLineColor8 = "#8C7D37"
dataSetBorderColor8 = "#808000"
dataSetBackgroundColor8 = "#808000"
dataSetErrorColor8 = "#808000"
dataSetLegendColor8 = "#94641F"
dataSetRowTitleColor8 = "#94641F"
dataSetBarFillColor9 = "#C0C000"
dataSetBarPatternColor9 = "#C0C000"
dataSetFillColor9 = "#C0C000"
dataSetLineColor9 = "#C0C000"
dataSetBorderColor9 = "#C0C000"
dataSetBackgroundColor9 = "#C0C000"
dataSetErrorColor9 = "#C0C000"
dataSetLegendColor9 = "#94641F"
dataSetRowTitleColor9 = "#94641F"
