pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#181818"
axisLabelColor = "#181818"
axisTitleColor = "#181818"
graphTitleColor = "#181818"
objectTextColor = "#181818"
objectFillColor = "#FFFFFF"
objectBorderColor = "#181818"
objectLinesColor = "#181818"
objectPatternColor = "#181818"
embeddedTableBorderColor = "#181818"
embeddedTableLineUnderTitleColor = "#181818"
embeddedTableLineNextToRowTitleColor = "#000000"
embeddedTableTextColor = "#181818"
embeddedTableGridColor = "#4E5246"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#A4553B"
dataSetBarPatternColor1 = "#A4553B"
dataSetFillColor1 = "#A4553B"
dataSetLineColor1 = "#6E1F00"
dataSetBorderColor1 = "#6E1F00"
dataSetBackgroundColor1 = "#A4553B"
dataSetErrorColor1 = "#6E1F00"
dataSetLegendColor1 = "#6E1F00"
dataSetRowTitleColor1 = "#6E1F00"
dataSetBarFillColor2 = "#9D3A5E"
dataSetBarPatternColor2 = "#9D3A5E"
dataSetFillColor2 = "#9D3A5E"
dataSetLineColor2 = "#58092C"
dataSetBorderColor2 = "#58092C"
dataSetBackgroundColor2 = "#9D3A5E"
dataSetErrorColor2 = "#58092C"
dataSetLegendColor2 = "#58092C"
dataSetRowTitleColor2 = "#58092C"
dataSetBarFillColor3 = "#5D7A2B"
dataSetBarPatternColor3 = "#5D7A2B"
dataSetFillColor3 = "#5D7A2B"
dataSetLineColor3 = "#254100"
dataSetBorderColor3 = "#254100"
dataSetBackgroundColor3 = "#5D7A2B"
dataSetErrorColor3 = "#254100"
dataSetLegendColor3 = "#254100"
dataSetRowTitleColor3 = "#254100"
dataSetBarFillColor4 = "#2C8169"
dataSetBarPatternColor4 = "#2C8169"
dataSetFillColor4 = "#2C8169"
dataSetLineColor4 = "#064233"
dataSetBorderColor4 = "#064233"
dataSetBackgroundColor4 = "#2C8169"
dataSetErrorColor4 = "#064233"
dataSetLegendColor4 = "#064233"
dataSetRowTitleColor4 = "#064233"
dataSetBarFillColor5 = "#4269A0"
dataSetBarPatternColor5 = "#4269A0"
dataSetFillColor5 = "#4269A0"
dataSetLineColor5 = "#263D5D"
dataSetBorderColor5 = "#263D5D"
dataSetBackgroundColor5 = "#4269A0"
dataSetErrorColor5 = "#263D5D"
dataSetLegendColor5 = "#263D5D"
dataSetRowTitleColor5 = "#263D5D"
dataSetBarFillColor6 = "#FF9444"
dataSetBarPatternColor6 = "#FF9444"
dataSetFillColor6 = "#FF9444"
dataSetLineColor6 = "#BD6345"
dataSetBorderColor6 = "#BD6345"
dataSetBackgroundColor6 = "#FF9444"
dataSetErrorColor6 = "#BD6345"
dataSetLegendColor6 = "#BD6345"
dataSetRowTitleColor6 = "#BD6345"
dataSetBarFillColor7 = "#D77B98"
dataSetBarPatternColor7 = "#D77B98"
dataSetFillColor7 = "#D77B98"
dataSetLineColor7 = "#9D3A5E"
dataSetBorderColor7 = "#9D3A5E"
dataSetBackgroundColor7 = "#D77B98"
dataSetErrorColor7 = "#9D3A5E"
dataSetLegendColor7 = "#9D3A5E"
dataSetRowTitleColor7 = "#9D3A5E"
dataSetBarFillColor8 = "#AFB76D"
dataSetBarPatternColor8 = "#AFB76D"
dataSetFillColor8 = "#AFB76D"
dataSetLineColor8 = "#5D7A2B"
dataSetBorderColor8 = "#5D7A2B"
dataSetBackgroundColor8 = "#AFB76D"
dataSetErrorColor8 = "#5D7A2B"
dataSetLegendColor8 = "#5D7A2B"
dataSetRowTitleColor8 = "#5D7A2B"
dataSetBarFillColor9 = "#6CC7B3"
dataSetBarPatternColor9 = "#6CC7B3"
dataSetFillColor9 = "#6CC7B3"
dataSetLineColor9 = "#2C8169"
dataSetBorderColor9 = "#2C8169"
dataSetBackgroundColor9 = "#6CC7B3"
dataSetErrorColor9 = "#2C8169"
dataSetLegendColor9 = "#2C8169"
dataSetRowTitleColor9 = "#2C8169"
dataSetBarFillColor10 = "#82A5D5"
dataSetBarPatternColor10 = "#82A5D5"
dataSetFillColor10 = "#82A5D5"
dataSetLineColor10 = "#4269A0"
dataSetBorderColor10 = "#4269A0"
dataSetBackgroundColor10 = "#82A5D5"
dataSetErrorColor10 = "#4269A0"
dataSetLegendColor10 = "#4269A0"
dataSetRowTitleColor10 = "#4269A0"
