pageBackgroundColor = "#000080"
plottingAreaColor = "#FFFFFF"
axisColor = "#F74ED6"
axisLabelColor = "#F74ED6"
axisTitleColor = "#F74ED6"
graphTitleColor = "#F74ED6"
objectTextColor = "#F74ED6"
objectFillColor = "#FFFFFF"
objectBorderColor = "#F74ED6"
objectLinesColor = "#F74ED6"
objectPatternColor = "#F74ED6"
embeddedTableBorderColor = "#F74ED6"
embeddedTableLineUnderTitleColor = "#F74ED6"
embeddedTableLineNextToRowTitleColor = "#F74ED6"
embeddedTableTextColor = "#F74ED6"
embeddedTableGridColor = "#F74ED6"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#FFFFFF"
dataSetBarPatternColor1 = "#00FF00"
dataSetFillColor1 = "#FFFFFF"
dataSetLineColor1 = "#00FF00"
dataSetBorderColor1 = "#FFFF00"
dataSetBackgroundColor1 = "#00FF00"
dataSetErrorColor1 = "#FFFF00"
dataSetLegendColor1 = "#F74ED6"
dataSetRowTitleColor1 = "#F74ED6"
dataSetBarFillColor2 = "#FFFFFF"
dataSetBarPatternColor2 = "#0000FF"
dataSetFillColor2 = "#FFFFFF"
dataSetLineColor2 = "#0000FF"
dataSetBorderColor2 = "#00FF00"
dataSetBackgroundColor2 = "#0000FF"
dataSetErrorColor2 = "#00FF00"
dataSetLegendColor2 = "#F74ED6"
dataSetRowTitleColor2 = "#F74ED6"
dataSetBarFillColor3 = "#FFFFFF"
dataSetBarPatternColor3 = "#F74ED6"
dataSetFillColor3 = "#FFFFFF"
dataSetLineColor3 = "#F74ED6"
dataSetBorderColor3 = "#F74ED6"
dataSetBackgroundColor3 = "#F74ED6"
dataSetErrorColor3 = "#F74ED6"
dataSetLegendColor3 = "#F74ED6"
dataSetRowTitleColor3 = "#F74ED6"
dataSetBarFillColor4 = "#FFFFFF"
dataSetBarPatternColor4 = "#FFFF00"
dataSetFillColor4 = "#FFFFFF"
dataSetLineColor4 = "#FFFF00"
dataSetBorderColor4 = "#FFFF00"
dataSetBackgroundColor4 = "#FFFF00"
dataSetErrorColor4 = "#FFFF00"
dataSetLegendColor4 = "#F74ED6"
dataSetRowTitleColor4 = "#F74ED6"
dataSetBarFillColor5 = "#FFFFFF"
dataSetBarPatternColor5 = "#00FF00"
dataSetFillColor5 = "#FFFFFF"
dataSetLineColor5 = "#00FF00"
dataSetBorderColor5 = "#00FF00"
dataSetBackgroundColor5 = "#00FF00"
dataSetErrorColor5 = "#00FF00"
dataSetLegendColor5 = "#F74ED6"
dataSetRowTitleColor5 = "#F74ED6"
dataSetBarFillColor6 = "#FFFFFF"
dataSetBarPatternColor6 = "#0000FF"
dataSetFillColor6 = "#FFFFFF"
dataSetLineColor6 = "#0000FF"
dataSetBorderColor6 = "#0000FF"
dataSetBackgroundColor6 = "#0000FF"
dataSetErrorColor6 = "#0000FF"
dataSetLegendColor6 = "#F74ED6"
dataSetRowTitleColor6 = "#F74ED6"
dataSetBarFillColor7 = "#FFFFFF"
dataSetBarPatternColor7 = "#FFFF00"
dataSetFillColor7 = "#FFFFFF"
dataSetLineColor7 = "#FFFF00"
dataSetBorderColor7 = "#FFFF00"
dataSetBackgroundColor7 = "#FFFF00"
dataSetErrorColor7 = "#FFFF00"
dataSetLegendColor7 = "#F74ED6"
dataSetRowTitleColor7 = "#F74ED6"
dataSetBarFillColor8 = "#FFFFFF"
dataSetBarPatternColor8 = "#0000FF"
dataSetFillColor8 = "#FFFFFF"
dataSetLineColor8 = "#0000FF"
dataSetBorderColor8 = "#0000FF"
dataSetBackgroundColor8 = "#0000FF"
dataSetErrorColor8 = "#0000FF"
dataSetLegendColor8 = "#F74ED6"
dataSetRowTitleColor8 = "#F74ED6"
dataSetBarFillColor9 = "#FFFFFF"
dataSetBarPatternColor9 = "#F74ED6"
dataSetFillColor9 = "#FFFFFF"
dataSetLineColor9 = "#F74ED6"
dataSetBorderColor9 = "#F74ED6"
dataSetBackgroundColor9 = "#F74ED6"
dataSetErrorColor9 = "#F74ED6"
dataSetLegendColor9 = "#F74ED6"
dataSetRowTitleColor9 = "#F74ED6"
