pageBackgroundColor = "#87CEFA"
plottingAreaColor = "#FFFFFF"
axisColor = "#FFFFCC"
axisLabelColor = "#FFFFCC"
axisTitleColor = "#3F71A3"
graphTitleColor = "#3F71A3"
objectTextColor = "#3F71A3"
objectFillColor = "#FFFFFF"
objectBorderColor = "#3F71A3"
objectLinesColor = "#3F71A3"
objectPatternColor = "#3F71A3"
embeddedTableBorderColor = "#3F71A3"
embeddedTableLineUnderTitleColor = "#3F71A3"
embeddedTableLineNextToRowTitleColor = "#3F71A3"
embeddedTableTextColor = "#3F71A3"
embeddedTableGridColor = "#3F71A3"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#F0E68C"
dataSetBarPatternColor1 = "#F0E68C"
dataSetFillColor1 = "#F0E68C"
dataSetLineColor1 = "#F0E68C"
dataSetBorderColor1 = "#808000"
dataSetBackgroundColor1 = "#F0E68C"
dataSetErrorColor1 = "#808000"
dataSetLegendColor1 = "#666699"
dataSetRowTitleColor1 = "#666699"
dataSetBarFillColor2 = "#FFFFCC"
dataSetBarPatternColor2 = "#FFFFCC"
dataSetFillColor2 = "#FFFFCC"
dataSetLineColor2 = "#FFFFCC"
dataSetBorderColor2 = "#FFFFCC"
dataSetBackgroundColor2 = "#FFFFCC"
dataSetErrorColor2 = "#FFFFCC"
dataSetLegendColor2 = "#666699"
dataSetRowTitleColor2 = "#666699"
dataSetBarFillColor3 = "#6699CC"
dataSetBarPatternColor3 = "#6699CC"
dataSetFillColor3 = "#6699CC"
dataSetLineColor3 = "#6699CC"
dataSetBorderColor3 = "#3F71A3"
dataSetBackgroundColor3 = "#6699CC"
dataSetErrorColor3 = "#3F71A3"
dataSetLegendColor3 = "#666699"
dataSetRowTitleColor3 = "#666699"
dataSetBarFillColor4 = "#CCCC00"
dataSetBarPatternColor4 = "#CCCC00"
dataSetFillColor4 = "#CCCC00"
dataSetLineColor4 = "#CCCC00"
dataSetBorderColor4 = "#808000"
dataSetBackgroundColor4 = "#CCCC00"
dataSetErrorColor4 = "#808000"
dataSetLegendColor4 = "#666699"
dataSetRowTitleColor4 = "#666699"
dataSetBarFillColor5 = "#C0C0C0"
dataSetBarPatternColor5 = "#C0C0C0"
dataSetFillColor5 = "#C0C0C0"
dataSetLineColor5 = "#C0C0C0"
dataSetBorderColor5 = "#666699"
dataSetBackgroundColor5 = "#C0C0C0"
dataSetErrorColor5 = "#666699"
dataSetLegendColor5 = "#666699"
dataSetRowTitleColor5 = "#666699"
dataSetBarFillColor6 = "#666699"
dataSetBarPatternColor6 = "#666699"
dataSetFillColor6 = "#666699"
dataSetLineColor6 = "#666699"
dataSetBorderColor6 = "#666699"
dataSetBackgroundColor6 = "#666699"
dataSetErrorColor6 = "#666699"
dataSetLegendColor6 = "#666699"
dataSetRowTitleColor6 = "#666699"
dataSetBarFillColor7 = "#FFFFCC"
dataSetBarPatternColor7 = "#FFFFCC"
dataSetFillColor7 = "#FFFFCC"
dataSetLineColor7 = "#FFFFCC"
dataSetBorderColor7 = "#FFFFCC"
dataSetBackgroundColor7 = "#FFFFCC"
dataSetErrorColor7 = "#FFFFCC"
dataSetLegendColor7 = "#666699"
dataSetRowTitleColor7 = "#666699"
dataSetBarFillColor8 = "#CCCC99"
dataSetBarPatternColor8 = "#CCCC99"
dataSetFillColor8 = "#CCCC99"
dataSetLineColor8 = "#CCCC99"
dataSetBorderColor8 = "#808000"
dataSetBackgroundColor8 = "#CCCC99"
dataSetErrorColor8 = "#808000"
dataSetLegendColor8 = "#666699"
dataSetRowTitleColor8 = "#000000"
dataSetBarFillColor9 = "#FFFFCC"
dataSetBarPatternColor9 = "#FFFFCC"
dataSetFillColor9 = "#FFFFCC"
dataSetLineColor9 = "#FFFFCC"
dataSetBorderColor9 = "#FFFFCC"
dataSetBackgroundColor9 = "#FFFFCC"
dataSetErrorColor9 = "#FFFFFF"
dataSetLegendColor9 = "#666699"
dataSetRowTitleColor9 = "#000000"
