pageBackgroundColor = "#CCD2E0"
plottingAreaColor = "#FFFFFF"
axisColor = "#000080"
axisLabelColor = "#000080"
axisTitleColor = "#000080"
graphTitleColor = "#000080"
objectTextColor = "#000080"
objectFillColor = "#FFFFFF"
objectBorderColor = "#000080"
objectLinesColor = "#000080"
objectPatternColor = "#000080"
embeddedTableBorderColor = "#000080"
embeddedTableLineUnderTitleColor = "#000080"
embeddedTableLineNextToRowTitleColor = "#000080"
embeddedTableTextColor = "#000080"
embeddedTableGridColor = "#000080"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#000080"
dataSetBarPatternColor1 = "#000080"
dataSetFillColor1 = "#000080"
dataSetLineColor1 = "#000080"
dataSetBorderColor1 = "#000080"
dataSetBackgroundColor1 = "#000080"
dataSetErrorColor1 = "#000080"
dataSetLegendColor1 = "#0000C0"
dataSetRowTitleColor1 = "#0000C0"
dataSetBarFillColor2 = "#800040"
dataSetBarPatternColor2 = "#800040"
dataSetFillColor2 = "#800040"
dataSetLineColor2 = "#800040"
dataSetBorderColor2 = "#800040"
dataSetBackgroundColor2 = "#800040"
dataSetErrorColor2 = "#800040"
dataSetLegendColor2 = "#800040"
dataSetRowTitleColor2 = "#800040"
dataSetBarFillColor3 = "#4C4C4C"
dataSetBarPatternColor3 = "#4C4C4C"
dataSetFillColor3 = "#4C4C4C"
dataSetLineColor3 = "#4C4C4C"
dataSetBorderColor3 = "#4C4C4C"
dataSetBackgroundColor3 = "#4C4C4C"
dataSetErrorColor3 = "#4C4C4C"
dataSetLegendColor3 = "#4C4C4C"
dataSetRowTitleColor3 = "#4C4C4C"
dataSetBarFillColor4 = "#008080"
dataSetBarPatternColor4 = "#008080"
dataSetFillColor4 = "#008080"
dataSetLineColor4 = "#008080"
dataSetBorderColor4 = "#008080"
dataSetBackgroundColor4 = "#008080"
dataSetErrorColor4 = "#008080"
dataSetLegendColor4 = "#008080"
dataSetRowTitleColor4 = "#008080"
dataSetBarFillColor5 = "#004080"
dataSetBarPatternColor5 = "#004080"
dataSetFillColor5 = "#004080"
dataSetLineColor5 = "#004080"
dataSetBorderColor5 = "#004080"
dataSetBackgroundColor5 = "#004080"
dataSetErrorColor5 = "#004080"
dataSetLegendColor5 = "#004080"
dataSetRowTitleColor5 = "#004080"
dataSetBarFillColor6 = "#800080"
dataSetBarPatternColor6 = "#800080"
dataSetFillColor6 = "#800080"
dataSetLineColor6 = "#800080"
dataSetBorderColor6 = "#800080"
dataSetBackgroundColor6 = "#800080"
dataSetErrorColor6 = "#800080"
dataSetLegendColor6 = "#800080"
dataSetRowTitleColor6 = "#800080"
dataSetBarFillColor7 = "#008040"
dataSetBarPatternColor7 = "#008040"
dataSetFillColor7 = "#008040"
dataSetLineColor7 = "#008040"
dataSetBorderColor7 = "#008040"
dataSetBackgroundColor7 = "#008040"
dataSetErrorColor7 = "#008040"
dataSetLegendColor7 = "#008040"
dataSetRowTitleColor7 = "#008040"
dataSetBarFillColor8 = "#0000FF"
dataSetBarPatternColor8 = "#0000FF"
dataSetFillColor8 = "#0000FF"
dataSetLineColor8 = "#0000FF"
dataSetBorderColor8 = "#0000FF"
dataSetBackgroundColor8 = "#0000FF"
dataSetErrorColor8 = "#0000FF"
dataSetLegendColor8 = "#0000C0"
dataSetRowTitleColor8 = "#0000C0"
dataSetBarFillColor9 = "#5757F9"
dataSetBarPatternColor9 = "#5757F9"
dataSetFillColor9 = "#5757F9"
dataSetLineColor9 = "#5757F9"
dataSetBorderColor9 = "#5757F9"
dataSetBackgroundColor9 = "#5757F9"
dataSetErrorColor9 = "#5757F9"
dataSetLegendColor9 = "#5757F9"
dataSetRowTitleColor9 = "#0000C0"
