pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#000000"
axisLabelColor = "#000000"
axisTitleColor = "#000000"
graphTitleColor = "#000000"
objectTextColor = "#000000"
objectFillColor = "#FFFFFF"
objectBorderColor = "#000000"
objectLinesColor = "#000000"
objectPatternColor = "#000000"
embeddedTableBorderColor = "#000000"
embeddedTableLineUnderTitleColor = "#000000"
embeddedTableLineNextToRowTitleColor = "#000000"
embeddedTableTextColor = "#000000"
embeddedTableGridColor = "#000000"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#000000"
dataSetBarPatternColor1 = "#000000"
dataSetFillColor1 = "#000000"
dataSetLineColor1 = "#000000"
dataSetBorderColor1 = "#000000"
dataSetBackgroundColor1 = "#000000"
dataSetErrorColor1 = "#000000"
dataSetLegendColor1 = "#000000"
dataSetRowTitleColor1 = "#000000"
dataSetBarFillColor2 = "#E8A761"
dataSetBarPatternColor2 = "#E8A761"
dataSetFillColor2 = "#E8A761"
dataSetLineColor2 = "#E8A761"
dataSetBorderColor2 = "#4D402F"
dataSetBackgroundColor2 = "#E8A761"
dataSetErrorColor2 = "#4D402F"
dataSetLegendColor2 = "#000000"
dataSetRowTitleColor2 = "#000000"
dataSetBarFillColor3 = "#9BB3D2"
dataSetBarPatternColor3 = "#9BB3D2"
dataSetFillColor3 = "#9BB3D2"
dataSetLineColor3 = "#9BB3D2"
dataSetBorderColor3 = "#22456F"
dataSetBackgroundColor3 = "#9BB3D2"
dataSetErrorColor3 = "#22456F"
dataSetLegendColor3 = "#000000"
dataSetRowTitleColor3 = "#000000"
dataSetBarFillColor4 = "#E5938A"
dataSetBarPatternColor4 = "#E5938A"
dataSetFillColor4 = "#E5938A"
dataSetLineColor4 = "#E5938A"
dataSetBorderColor4 = "#B63530"
dataSetBackgroundColor4 = "#E5938A"
dataSetErrorColor4 = "#B63530"
dataSetLegendColor4 = "#000000"
dataSetRowTitleColor4 = "#000000"
dataSetBarFillColor5 = "#BDC1C4"
dataSetBarPatternColor5 = "#BDC1C4"
dataSetFillColor5 = "#BDC1C4"
dataSetLineColor5 = "#BDC1C4"
dataSetBorderColor5 = "#85827A"
dataSetBackgroundColor5 = "#BDC1C4"
dataSetErrorColor5 = "#85827A"
dataSetLegendColor5 = "#000000"
dataSetRowTitleColor5 = "#000000"
dataSetBarFillColor6 = "#F2CEC0"
dataSetBarPatternColor6 = "#F2CEC0"
dataSetFillColor6 = "#F2CEC0"
dataSetLineColor6 = "#F2CEC0"
dataSetBorderColor6 = "#705443"
dataSetBackgroundColor6 = "#F2CEC0"
dataSetErrorColor6 = "#705443"
dataSetLegendColor6 = "#000000"
dataSetRowTitleColor6 = "#000000"
