pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#000000"
axisLabelColor = "#000000"
axisTitleColor = "#000000"
graphTitleColor = "#000000"
objectTextColor = "#000000"
objectFillColor = "#FFFFFF"
objectBorderColor = "#000000"
objectLinesColor = "#000000"
objectPatternColor = "#000000"
embeddedTableBorderColor = "#000000"
embeddedTableLineUnderTitleColor = "#000000"
embeddedTableLineNextToRowTitleColor = "#000000"
embeddedTableTextColor = "#000000"
embeddedTableGridColor = "#000000"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#0D0887"
dataSetBarPatternColor1 = "#0D0887"
dataSetFillColor1 = "#0D0887"
dataSetLineColor1 = "#0D0887"
dataSetBorderColor1 = "#000000"
dataSetBackgroundColor1 = "#0D0887"
dataSetErrorColor1 = "#000000"
dataSetLegendColor1 = "#000000"
dataSetRowTitleColor1 = "#0D0887"
dataSetBarFillColor2 = "#6A00A8"
dataSetBarPatternColor2 = "#6A00A8"
dataSetFillColor2 = "#6A00A8"
dataSetLineColor2 = "#6A00A8"
dataSetBorderColor2 = "#000000"
dataSetBackgroundColor2 = "#6A00A8"
dataSetErrorColor2 = "#000000"
dataSetLegendColor2 = "#000000"
dataSetRowTitleColor2 = "#6A00A8"
dataSetBarFillColor3 = "#B12A90"
dataSetBarPatternColor3 = "#B12A90"
dataSetFillColor3 = "#B12A90"
dataSetLineColor3 = "#B12A90"
dataSetBorderColor3 = "#000000"
dataSetBackgroundColor3 = "#B12A90"
dataSetErrorColor3 = "#000000"
dataSetLegendColor3 = "#000000"
dataSetRowTitleColor3 = "#B12A90"
dataSetBarFillColor4 = "#E16462"
dataSetBarPatternColor4 = "#E16462"
dataSetFillColor4 = "#E16462"
dataSetLineColor4 = "#E16462"
dataSetBorderColor4 = "#000000"
dataSetBackgroundColor4 = "#E16462"
dataSetErrorColor4 = "#000000"
dataSetLegendColor4 = "#000000"
dataSetRowTitleColor4 = "#E16462"
dataSetBarFillColor5 = "#FCA636"
dataSetBarPatternColor5 = "#FCA636"
dataSetFillColor5 = "#FCA636"
dataSetLineColor5 = "#FCA636"
dataSetBorderColor5 = "#000000"
dataSetBackgroundColor5 = "#FCA636"
dataSetErrorColor5 = "#000000"
dataSetLegendColor5 = "#000000"
dataSetRowTitleColor5 = "#FCA636"
dataSetBarFillColor6 = "#F0F921"
dataSetBarPatternColor6 = "#F0F921"
dataSetFillColor6 = "#F0F921"
dataSetLineColor6 = "#F0F921"
dataSetBorderColor6 = "#000000"
dataSetBackgroundColor6 = "#F0F921"
dataSetErrorColor6 = "#000000"
dataSetLegendColor6 = "#000000"
dataSetRowTitleColor6 = "#F0F820"
