pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#000000"
axisLabelColor = "#000000"
axisTitleColor = "#000000"
graphTitleColor = "#000000"
objectTextColor = "#000000"
objectFillColor = "#FFFFFF"
objectBorderColor = "#000000"
objectLinesColor = "#000000"
objectPatternColor = "#000000"
embeddedTableBorderColor = "#000000"
embeddedTableLineUnderTitleColor = "#000000"
embeddedTableLineNextToRowTitleColor = "#000000"
embeddedTableTextColor = "#000000"
embeddedTableGridColor = "#000000"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#A48AD3"
dataSetBarPatternColor1 = "#A48AD3"
dataSetFillColor1 = "#A48AD3"
dataSetLineColor1 = "#A48AD3"
dataSetBorderColor1 = "#2C1453"
dataSetBackgroundColor1 = "#A48AD3"
dataSetErrorColor1 = "#2C1453"
dataSetLegendColor1 = "#000000"
dataSetRowTitleColor1 = "#000000"
dataSetBarFillColor2 = "#1CC5FE"
dataSetBarPatternColor2 = "#1CC5FE"
dataSetFillColor2 = "#1CC5FE"
dataSetLineColor2 = "#1CC5FE"
dataSetBorderColor2 = "#114CE8"
dataSetBackgroundColor2 = "#1CC5FE"
dataSetErrorColor2 = "#114CE8"
dataSetLegendColor2 = "#000000"
dataSetRowTitleColor2 = "#000000"
dataSetBarFillColor3 = "#6FC7CF"
dataSetBarPatternColor3 = "#6FC7CF"
dataSetFillColor3 = "#6FC7CF"
dataSetLineColor3 = "#6FC7CF"
dataSetBorderColor3 = "#0E6F7C"
dataSetBackgroundColor3 = "#6FC7CF"
dataSetErrorColor3 = "#0E6F7C"
dataSetLegendColor3 = "#000000"
dataSetRowTitleColor3 = "#000000"
dataSetBarFillColor4 = "#FBA27D"
dataSetBarPatternColor4 = "#FBA27D"
dataSetFillColor4 = "#FBA27D"
dataSetLineColor4 = "#FBA27D"
dataSetBorderColor4 = "#FB4F06"
dataSetBackgroundColor4 = "#FBA27D"
dataSetErrorColor4 = "#FB4F06"
dataSetLegendColor4 = "#000000"
dataSetRowTitleColor4 = "#000000"
dataSetBarFillColor5 = "#FB7D80"
dataSetBarPatternColor5 = "#FB7D80"
dataSetFillColor5 = "#FB7D80"
dataSetLineColor5 = "#FB7D80"
dataSetBorderColor5 = "#FB0005"
dataSetBackgroundColor5 = "#FB7D80"
dataSetErrorColor5 = "#FB0005"
dataSetLegendColor5 = "#000000"
dataSetRowTitleColor5 = "#000000"
dataSetBarFillColor6 = "#2C1453"
dataSetBarPatternColor6 = "#2C1453"
dataSetFillColor6 = "#2C1453"
dataSetLineColor6 = "#2C1453"
dataSetBorderColor6 = "#A48AD3"
dataSetBackgroundColor6 = "#2C1453"
dataSetErrorColor6 = "#A48AD3"
dataSetLegendColor6 = "#000000"
dataSetRowTitleColor6 = "#000000"
dataSetBarFillColor7 = "#114CE8"
dataSetBarPatternColor7 = "#114CE8"
dataSetFillColor7 = "#114CE8"
dataSetLineColor7 = "#114CE8"
dataSetBorderColor7 = "#1CC5FE"
dataSetBackgroundColor7 = "#114CE8"
dataSetErrorColor7 = "#1CC5FE"
dataSetLegendColor7 = "#000000"
dataSetRowTitleColor7 = "#000000"
dataSetBarFillColor8 = "#0E6F7C"
dataSetBarPatternColor8 = "#0E6F7C"
dataSetFillColor8 = "#0E6F7C"
dataSetLineColor8 = "#0E6F7C"
dataSetBorderColor8 = "#6FC7CF"
dataSetBackgroundColor8 = "#0E6F7C"
dataSetErrorColor8 = "#6FC7CF"
dataSetLegendColor8 = "#000000"
dataSetRowTitleColor8 = "#000000"
dataSetBarFillColor9 = "#FB4F06"
dataSetBarPatternColor9 = "#FB4F06"
dataSetFillColor9 = "#FB4F06"
dataSetLineColor9 = "#FB4F06"
dataSetBorderColor9 = "#FBA27D"
dataSetBackgroundColor9 = "#FB4F06"
dataSetErrorColor9 = "#FBA27D"
dataSetLegendColor9 = "#000000"
dataSetRowTitleColor9 = "#000000"
dataSetBarFillColor10 = "#FB0005"
dataSetBarPatternColor10 = "#FB0005"
dataSetFillColor10 = "#FB0005"
dataSetLineColor10 = "#FB0005"
dataSetBorderColor10 = "#FB7D80"
dataSetBackgroundColor10 = "#FB0005"
dataSetErrorColor10 = "#FB7D80"
dataSetLegendColor10 = "#000000"
dataSetRowTitleColor10 = "#000000"
