pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#76069A"
axisLabelColor = "#76069A"
axisTitleColor = "#76069A"
graphTitleColor = "#76069A"
objectTextColor = "#76069A"
objectFillColor = "#FFFFFF"
objectBorderColor = "#76069A"
objectLinesColor = "#76069A"
objectPatternColor = "#76069A"
embeddedTableBorderColor = "#76069A"
embeddedTableLineUnderTitleColor = "#76069A"
embeddedTableLineNextToRowTitleColor = "#76069A"
embeddedTableTextColor = "#76069A"
embeddedTableGridColor = "#76069A"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#76069A"
dataSetBarPatternColor1 = "#76069A"
dataSetFillColor1 = "#76069A"
dataSetLineColor1 = "#76069A"
dataSetBorderColor1 = "#76069A"
dataSetBackgroundColor1 = "#76069A"
dataSetErrorColor1 = "#76069A"
dataSetLegendColor1 = "#76069A"
dataSetRowTitleColor1 = "#76069A"
dataSetBarFillColor2 = "#AD07E3"
dataSetBarPatternColor2 = "#AD07E3"
dataSetFillColor2 = "#AD07E3"
dataSetLineColor2 = "#AD07E3"
dataSetBorderColor2 = "#AD07E3"
dataSetBackgroundColor2 = "#AD07E3"
dataSetErrorColor2 = "#AD07E3"
dataSetLegendColor2 = "#76069A"
dataSetRowTitleColor2 = "#76069A"
dataSetBarFillColor3 = "#F74ED6"
dataSetBarPatternColor3 = "#F74ED6"
dataSetFillColor3 = "#F74ED6"
dataSetLineColor3 = "#F74ED6"
dataSetBorderColor3 = "#F74ED6"
dataSetBackgroundColor3 = "#F74ED6"
dataSetErrorColor3 = "#F74ED6"
dataSetLegendColor3 = "#76069A"
dataSetRowTitleColor3 = "#76069A"
dataSetBarFillColor4 = "#B856D7"
dataSetBarPatternColor4 = "#B856D7"
dataSetFillColor4 = "#B856D7"
dataSetLineColor4 = "#B856D7"
dataSetBorderColor4 = "#B856D7"
dataSetBackgroundColor4 = "#B856D7"
dataSetErrorColor4 = "#B856D7"
dataSetLegendColor4 = "#76069A"
dataSetRowTitleColor4 = "#76069A"
dataSetBarFillColor5 = "#DE8BF9"
dataSetBarPatternColor5 = "#DE8BF9"
dataSetFillColor5 = "#DE8BF9"
dataSetLineColor5 = "#DE8BF9"
dataSetBorderColor5 = "#DE8BF9"
dataSetBackgroundColor5 = "#DE8BF9"
dataSetErrorColor5 = "#DE8BF9"
dataSetLegendColor5 = "#76069A"
dataSetRowTitleColor5 = "#76069A"
dataSetBarFillColor6 = "#F71480"
dataSetBarPatternColor6 = "#F71480"
dataSetFillColor6 = "#F71480"
dataSetLineColor6 = "#F71480"
dataSetBorderColor6 = "#F71480"
dataSetBackgroundColor6 = "#F71480"
dataSetErrorColor6 = "#F71480"
dataSetLegendColor6 = "#76069A"
dataSetRowTitleColor6 = "#76069A"
dataSetBarFillColor7 = "#F7ABE8"
dataSetBarPatternColor7 = "#F7ABE8"
dataSetFillColor7 = "#F7ABE8"
dataSetLineColor7 = "#F7ABE8"
dataSetBorderColor7 = "#F7ABE8"
dataSetBackgroundColor7 = "#F7ABE8"
dataSetErrorColor7 = "#F7ABE8"
dataSetLegendColor7 = "#76069A"
dataSetRowTitleColor7 = "#76069A"
dataSetBarFillColor8 = "#B07FC0"
dataSetBarPatternColor8 = "#B07FC0"
dataSetFillColor8 = "#B07FC0"
dataSetLineColor8 = "#B07FC0"
dataSetBorderColor8 = "#B07FC0"
dataSetBackgroundColor8 = "#B07FC0"
dataSetErrorColor8 = "#B07FC0"
dataSetLegendColor8 = "#76069A"
dataSetRowTitleColor8 = "#76069A"
dataSetBarFillColor9 = "#D614AF"
dataSetBarPatternColor9 = "#D614AF"
dataSetFillColor9 = "#D614AF"
dataSetLineColor9 = "#D614AF"
dataSetBorderColor9 = "#D614AF"
dataSetBackgroundColor9 = "#D614AF"
dataSetErrorColor9 = "#D614AF"
dataSetLegendColor9 = "#76069A"
dataSetRowTitleColor9 = "#76069A"
