pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#999966"
axisLabelColor = "#336666"
axisTitleColor = "#336666"
graphTitleColor = "#336666"
objectTextColor = "#336666"
objectFillColor = "#FFFFFF"
objectBorderColor = "#999966"
objectLinesColor = "#336666"
objectPatternColor = "#999966"
embeddedTableBorderColor = "#999966"
embeddedTableLineUnderTitleColor = "#999966"
embeddedTableLineNextToRowTitleColor = "#999966"
embeddedTableTextColor = "#336666"
embeddedTableGridColor = "#999966"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#006666"
dataSetBarPatternColor1 = "#006666"
dataSetFillColor1 = "#006666"
dataSetLineColor1 = "#006666"
dataSetBorderColor1 = "#006666"
dataSetBackgroundColor1 = "#006666"
dataSetErrorColor1 = "#006666"
dataSetLegendColor1 = "#006666"
dataSetRowTitleColor1 = "#000000"
dataSetBarFillColor2 = "#CCCC99"
dataSetBarPatternColor2 = "#CCCC99"
dataSetFillColor2 = "#CCCC99"
dataSetLineColor2 = "#CCCC99"
dataSetBorderColor2 = "#999966"
dataSetBackgroundColor2 = "#CCCC99"
dataSetErrorColor2 = "#CCCC99"
dataSetLegendColor2 = "#006666"
dataSetRowTitleColor2 = "#000000"
dataSetBarFillColor3 = "#999966"
dataSetBarPatternColor3 = "#999966"
dataSetFillColor3 = "#999966"
dataSetLineColor3 = "#999966"
dataSetBorderColor3 = "#999966"
dataSetBackgroundColor3 = "#999966"
dataSetErrorColor3 = "#999966"
dataSetLegendColor3 = "#006666"
dataSetRowTitleColor3 = "#000000"
dataSetBarFillColor4 = "#99CCCC"
dataSetBarPatternColor4 = "#99CCCC"
dataSetFillColor4 = "#99CCCC"
dataSetLineColor4 = "#99CCCC"
dataSetBorderColor4 = "#336666"
dataSetBackgroundColor4 = "#99CCCC"
dataSetErrorColor4 = "#99CCCC"
dataSetLegendColor4 = "#006666"
dataSetRowTitleColor4 = "#000000"
dataSetBarFillColor5 = "#6C6935"
dataSetBarPatternColor5 = "#6C6935"
dataSetFillColor5 = "#6C6935"
dataSetLineColor5 = "#6C6935"
dataSetBorderColor5 = "#6C6935"
dataSetBackgroundColor5 = "#6C6935"
dataSetErrorColor5 = "#6C6935"
dataSetLegendColor5 = "#006666"
dataSetRowTitleColor5 = "#000000"
dataSetBarFillColor6 = "#CCCC99"
dataSetBarPatternColor6 = "#CCCC99"
dataSetFillColor6 = "#CCCC99"
dataSetLineColor6 = "#CCCC99"
dataSetBorderColor6 = "#CCCC99"
dataSetBackgroundColor6 = "#CCCC99"
dataSetErrorColor6 = "#CCCC99"
dataSetLegendColor6 = "#006666"
dataSetRowTitleColor6 = "#000000"
dataSetBarFillColor7 = "#999966"
dataSetBarPatternColor7 = "#999966"
dataSetFillColor7 = "#999966"
dataSetLineColor7 = "#999966"
dataSetBorderColor7 = "#999966"
dataSetBackgroundColor7 = "#999966"
dataSetErrorColor7 = "#999966"
dataSetLegendColor7 = "#006666"
dataSetRowTitleColor7 = "#000000"
dataSetBarFillColor8 = "#F0E68C"
dataSetBarPatternColor8 = "#F0E68C"
dataSetFillColor8 = "#F0E68C"
dataSetLineColor8 = "#F0E68C"
dataSetBorderColor8 = "#999966"
dataSetBackgroundColor8 = "#F0E68C"
dataSetErrorColor8 = "#F0E68C"
dataSetLegendColor8 = "#006666"
dataSetRowTitleColor8 = "#000000"
dataSetBarFillColor9 = "#336666"
dataSetBarPatternColor9 = "#336666"
dataSetFillColor9 = "#336666"
dataSetLineColor9 = "#336666"
dataSetBorderColor9 = "#336666"
dataSetBackgroundColor9 = "#336666"
dataSetErrorColor9 = "#336666"
dataSetLegendColor9 = "#336666"
dataSetRowTitleColor9 = "#000000"
