pageBackgroundColor = "#B4F99F"
plottingAreaColor = "#FFFFFF"
axisColor = "#4169E1"
axisLabelColor = "#4169E1"
axisTitleColor = "#4169E1"
graphTitleColor = "#4169E1"
objectTextColor = "#4169E1"
objectFillColor = "#FFFFFF"
objectBorderColor = "#4169E1"
objectLinesColor = "#4169E1"
objectPatternColor = "#4169E1"
embeddedTableBorderColor = "#4169E1"
embeddedTableLineUnderTitleColor = "#4169E1"
embeddedTableLineNextToRowTitleColor = "#4169E1"
embeddedTableTextColor = "#4169E1"
embeddedTableGridColor = "#4169E1"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#CAFFCA"
dataSetBarFillColor1 = "#1E90FF"
dataSetBarPatternColor1 = "#1E90FF"
dataSetFillColor1 = "#1E90FF"
dataSetLineColor1 = "#1E90FF"
dataSetBorderColor1 = "#1E90FF"
dataSetBackgroundColor1 = "#1E90FF"
dataSetErrorColor1 = "#1E90FF"
dataSetLegendColor1 = "#4169E1"
dataSetRowTitleColor1 = "#000000"
dataSetBarFillColor2 = "#FFFFFF"
dataSetBarPatternColor2 = "#FFFFFF"
dataSetFillColor2 = "#FFFFFF"
dataSetLineColor2 = "#FFFFFF"
dataSetBorderColor2 = "#3F71A3"
dataSetBackgroundColor2 = "#FFFFFF"
dataSetErrorColor2 = "#3F71A3"
dataSetLegendColor2 = "#4169E1"
dataSetRowTitleColor2 = "#000000"
dataSetBarFillColor3 = "#FFFF00"
dataSetBarPatternColor3 = "#FFFF00"
dataSetFillColor3 = "#FFFF00"
dataSetLineColor3 = "#FFFF00"
dataSetBorderColor3 = "#FFA040"
dataSetBackgroundColor3 = "#FFFF00"
dataSetErrorColor3 = "#FFA040"
dataSetLegendColor3 = "#4169E1"
dataSetRowTitleColor3 = "#000000"
dataSetBarFillColor4 = "#FFCC00"
dataSetBarPatternColor4 = "#FFCC00"
dataSetFillColor4 = "#FFCC00"
dataSetLineColor4 = "#FFCC00"
dataSetBorderColor4 = "#FF8000"
dataSetBackgroundColor4 = "#FFCC00"
dataSetErrorColor4 = "#FF8000"
dataSetLegendColor4 = "#4169E1"
dataSetRowTitleColor4 = "#000000"
dataSetBarFillColor5 = "#90EE90"
dataSetBarPatternColor5 = "#90EE90"
dataSetFillColor5 = "#90EE90"
dataSetLineColor5 = "#90EE90"
dataSetBorderColor5 = "#279D00"
dataSetBackgroundColor5 = "#90EE90"
dataSetErrorColor5 = "#279D00"
dataSetLegendColor5 = "#4169E1"
dataSetRowTitleColor5 = "#000000"
dataSetBarFillColor6 = "#33CC00"
dataSetBarPatternColor6 = "#33CC00"
dataSetFillColor6 = "#33CC00"
dataSetLineColor6 = "#33CC00"
dataSetBorderColor6 = "#008000"
dataSetBackgroundColor6 = "#33CC00"
dataSetErrorColor6 = "#008000"
dataSetLegendColor6 = "#4169E1"
dataSetRowTitleColor6 = "#000000"
dataSetBarFillColor7 = "#CC6699"
dataSetBarPatternColor7 = "#CC6699"
dataSetFillColor7 = "#CC6699"
dataSetLineColor7 = "#CC6699"
dataSetBorderColor7 = "#CC6699"
dataSetBackgroundColor7 = "#CC6699"
dataSetErrorColor7 = "#CC6699"
dataSetLegendColor7 = "#4169E1"
dataSetRowTitleColor7 = "#000000"
dataSetBarFillColor8 = "#FF99FF"
dataSetBarPatternColor8 = "#FF99FF"
dataSetFillColor8 = "#FF99FF"
dataSetLineColor8 = "#FF99FF"
dataSetBorderColor8 = "#CC6699"
dataSetBackgroundColor8 = "#FF99FF"
dataSetErrorColor8 = "#CC6699"
dataSetLegendColor8 = "#4169E1"
dataSetRowTitleColor8 = "#000000"
dataSetBarFillColor9 = "#9DF8FF"
dataSetBarPatternColor9 = "#9DF8FF"
dataSetFillColor9 = "#9DF8FF"
dataSetLineColor9 = "#9DF8FF"
dataSetBorderColor9 = "#6699CC"
dataSetBackgroundColor9 = "#9DF8FF"
dataSetErrorColor9 = "#6699CC"
dataSetLegendColor9 = "#4169E1"
dataSetRowTitleColor9 = "#000000"
