pageBackgroundColor = "#000000"
plottingAreaColor = "#FFFFFF"
axisColor = "#D4D4D4"
axisLabelColor = "#FFFFFF"
axisTitleColor = "#FFFFFF"
graphTitleColor = "#FFFFFF"
objectTextColor = "#FFFFFF"
objectFillColor = "#FFFFFF"
objectBorderColor = "#FFFFFF"
objectLinesColor = "#FFFFFF"
objectPatternColor = "#FFFFFF"
embeddedTableBorderColor = "#FFFFFF"
embeddedTableLineUnderTitleColor = "#FFFFFF"
embeddedTableLineNextToRowTitleColor = "#FFFFFF"
embeddedTableTextColor = "#FFFFFF"
embeddedTableGridColor = "#FFFFFF"
embeddedTablePatternColor = "#000000"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#FF0000"
dataSetBarPatternColor1 = "#FF0000"
dataSetFillColor1 = "#FF0000"
dataSetLineColor1 = "#FF0000"
dataSetBorderColor1 = "#FF0000"
dataSetBackgroundColor1 = "#FF0000"
dataSetErrorColor1 = "#FF0000"
dataSetLegendColor1 = "#FF0000"
dataSetRowTitleColor1 = "#FFFFFF"
dataSetBarFillColor2 = "#FFFF00"
dataSetBarPatternColor2 = "#FFFF00"
dataSetFillColor2 = "#FFFF00"
dataSetLineColor2 = "#FFFF00"
dataSetBorderColor2 = "#FFFF00"
dataSetBackgroundColor2 = "#FFFF00"
dataSetErrorColor2 = "#FFFF00"
dataSetLegendColor2 = "#FFFF00"
dataSetRowTitleColor2 = "#FFFFFF"
dataSetBarFillColor3 = "#00FF00"
dataSetBarPatternColor3 = "#00FF00"
dataSetFillColor3 = "#00FF00"
dataSetLineColor3 = "#00FF00"
dataSetBorderColor3 = "#00FF00"
dataSetBackgroundColor3 = "#00FF00"
dataSetErrorColor3 = "#00FF00"
dataSetLegendColor3 = "#00FF00"
dataSetRowTitleColor3 = "#FFFFFF"
dataSetBarFillColor4 = "#55A0FB"
dataSetBarPatternColor4 = "#55A0FB"
dataSetFillColor4 = "#55A0FB"
dataSetLineColor4 = "#55A0FB"
dataSetBorderColor4 = "#55A0FB"
dataSetBackgroundColor4 = "#55A0FB"
dataSetErrorColor4 = "#55A0FB"
dataSetLegendColor4 = "#55A0FB"
dataSetRowTitleColor4 = "#FFFFFF"
dataSetBarFillColor5 = "#B856D7"
dataSetBarPatternColor5 = "#B856D7"
dataSetFillColor5 = "#B856D7"
dataSetLineColor5 = "#B856D7"
dataSetBorderColor5 = "#B856D7"
dataSetBackgroundColor5 = "#B856D7"
dataSetErrorColor5 = "#B856D7"
dataSetLegendColor5 = "#B07FC0"
dataSetRowTitleColor5 = "#FFFFFF"
dataSetBarFillColor6 = "#F74ED6"
dataSetBarPatternColor6 = "#F74ED6"
dataSetFillColor6 = "#F74ED6"
dataSetLineColor6 = "#F74ED6"
dataSetBorderColor6 = "#F74ED6"
dataSetBackgroundColor6 = "#F74ED6"
dataSetErrorColor6 = "#F74ED6"
dataSetLegendColor6 = "#F74ED6"
dataSetRowTitleColor6 = "#FFFFFF"
dataSetBarFillColor7 = "#FF8000"
dataSetBarPatternColor7 = "#FF8000"
dataSetFillColor7 = "#FF8000"
dataSetLineColor7 = "#FF8000"
dataSetBorderColor7 = "#FF8000"
dataSetBackgroundColor7 = "#FF8000"
dataSetErrorColor7 = "#FF8000"
dataSetLegendColor7 = "#FF8000"
dataSetRowTitleColor7 = "#FFFFFF"
dataSetBarFillColor8 = "#0000C0"
dataSetBarPatternColor8 = "#0000C0"
dataSetFillColor8 = "#0000C0"
dataSetLineColor8 = "#0000C0"
dataSetBorderColor8 = "#0000C0"
dataSetBackgroundColor8 = "#0000C0"
dataSetErrorColor8 = "#0000C0"
dataSetLegendColor8 = "#0000C0"
dataSetRowTitleColor8 = "#FFFFFF"
dataSetBarFillColor9 = "#FFFF00"
dataSetBarPatternColor9 = "#FFFF00"
dataSetFillColor9 = "#FFFF00"
dataSetLineColor9 = "#00C000"
dataSetBorderColor9 = "#00C000"
dataSetBackgroundColor9 = "#FFFF00"
dataSetErrorColor9 = "#FFFF00"
dataSetLegendColor9 = "#FFFF00"
dataSetRowTitleColor9 = "#FFFFFF"
