pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#000000"
axisLabelColor = "#000000"
axisTitleColor = "#000000"
graphTitleColor = "#000000"
objectTextColor = "#000000"
objectFillColor = "#FFFFFF"
objectBorderColor = "#000000"
objectLinesColor = "#000000"
objectPatternColor = "#000000"
embeddedTableBorderColor = "#000000"
embeddedTableLineUnderTitleColor = "#000000"
embeddedTableLineNextToRowTitleColor = "#000000"
embeddedTableTextColor = "#000000"
embeddedTableGridColor = "#000000"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#323232"
dataSetBarPatternColor1 = "#323232"
dataSetFillColor1 = "#323232"
dataSetLineColor1 = "#323232"
dataSetBorderColor1 = "#000000"
dataSetBackgroundColor1 = "#323232"
dataSetErrorColor1 = "#000000"
dataSetLegendColor1 = "#000000"
dataSetRowTitleColor1 = "#000000"
dataSetBarFillColor2 = "#1B6393"
dataSetBarPatternColor2 = "#1B6393"
dataSetFillColor2 = "#1B6393"
dataSetLineColor2 = "#1B6393"
dataSetBorderColor2 = "#042E3D"
dataSetBackgroundColor2 = "#1B6393"
dataSetErrorColor2 = "#042E3D"
dataSetLegendColor2 = "#000000"
dataSetRowTitleColor2 = "#000000"
dataSetBarFillColor3 = "#FCD351"
dataSetBarPatternColor3 = "#FCD351"
dataSetFillColor3 = "#FCD351"
dataSetLineColor3 = "#FCD351"
dataSetBorderColor3 = "#765A22"
dataSetBackgroundColor3 = "#FCD351"
dataSetErrorColor3 = "#765A22"
dataSetLegendColor3 = "#000000"
dataSetRowTitleColor3 = "#000000"
dataSetBarFillColor4 = "#C7E3CC"
dataSetBarPatternColor4 = "#C7E3CC"
dataSetFillColor4 = "#C7E3CC"
dataSetLineColor4 = "#C7E3CC"
dataSetBorderColor4 = "#44726D"
dataSetBackgroundColor4 = "#C7E3CC"
dataSetErrorColor4 = "#44726D"
dataSetLegendColor4 = "#000000"
dataSetRowTitleColor4 = "#000000"
dataSetBarFillColor5 = "#F8EEC1"
dataSetBarPatternColor5 = "#F8EEC1"
dataSetFillColor5 = "#F8EEC1"
dataSetLineColor5 = "#F8EEC1"
dataSetBorderColor5 = "#9A9343"
dataSetBackgroundColor5 = "#F8EEC1"
dataSetErrorColor5 = "#9A9343"
dataSetLegendColor5 = "#000000"
dataSetRowTitleColor5 = "#000000"
