pageBackgroundColor = "#FFF6B9"
plottingAreaColor = "#FFFFFF"
axisColor = "#181818"
axisLabelColor = "#181818"
axisTitleColor = "#181818"
graphTitleColor = "#181818"
objectTextColor = "#181818"
objectFillColor = "#FFFFFF"
objectBorderColor = "#181818"
objectLinesColor = "#181818"
objectPatternColor = "#181818"
embeddedTableBorderColor = "#181818"
embeddedTableLineUnderTitleColor = "#181818"
embeddedTableLineNextToRowTitleColor = "#181818"
embeddedTableTextColor = "#181818"
embeddedTableGridColor = "#4E5246"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#7DA1D5"
dataSetBarPatternColor1 = "#7DA1D5"
dataSetFillColor1 = "#7DA1D5"
dataSetLineColor1 = "#285291"
dataSetBorderColor1 = "#285291"
dataSetBackgroundColor1 = "#7DA1D5"
dataSetErrorColor1 = "#285291"
dataSetLegendColor1 = "#285291"
dataSetRowTitleColor1 = "#285291"
dataSetBarFillColor2 = "#BDDE85"
dataSetBarPatternColor2 = "#BDDE85"
dataSetFillColor2 = "#BDDE85"
dataSetLineColor2 = "#579125"
dataSetBorderColor2 = "#579125"
dataSetBackgroundColor2 = "#BDDE85"
dataSetErrorColor2 = "#579125"
dataSetLegendColor2 = "#579125"
dataSetRowTitleColor2 = "#579125"
dataSetBarFillColor3 = "#DDAF70"
dataSetBarPatternColor3 = "#DDAF70"
dataSetFillColor3 = "#DDAF70"
dataSetLineColor3 = "#915B11"
dataSetBorderColor3 = "#915B11"
dataSetBackgroundColor3 = "#DDAF70"
dataSetErrorColor3 = "#915B11"
dataSetLegendColor3 = "#915B11"
dataSetRowTitleColor3 = "#915B11"
dataSetBarFillColor4 = "#DE767C"
dataSetBarPatternColor4 = "#DE767C"
dataSetFillColor4 = "#DE767C"
dataSetLineColor4 = "#91181E"
dataSetBorderColor4 = "#91181E"
dataSetBackgroundColor4 = "#DE767C"
dataSetErrorColor4 = "#91181E"
dataSetLegendColor4 = "#91181E"
dataSetRowTitleColor4 = "#91181E"
dataSetBarFillColor5 = "#EA95EB"
dataSetBarPatternColor5 = "#EA95EB"
dataSetFillColor5 = "#EA95EB"
dataSetLineColor5 = "#91188F"
dataSetBorderColor5 = "#91188F"
dataSetBackgroundColor5 = "#EA95EB"
dataSetErrorColor5 = "#91188F"
dataSetLegendColor5 = "#91188F"
dataSetRowTitleColor5 = "#91188F"
dataSetBarFillColor6 = "#A58BD4"
dataSetBarPatternColor6 = "#A58BD4"
dataSetFillColor6 = "#A58BD4"
dataSetLineColor6 = "#4F2B91"
dataSetBorderColor6 = "#4F2B91"
dataSetBackgroundColor6 = "#A58BD4"
dataSetErrorColor6 = "#4F2B91"
dataSetLegendColor6 = "#4F2B91"
dataSetRowTitleColor6 = "#4F2B91"
dataSetBarFillColor7 = "#53629E"
dataSetBarPatternColor7 = "#53629E"
dataSetFillColor7 = "#53629E"
dataSetLineColor7 = "#0F0F5C"
dataSetBorderColor7 = "#0F0F5C"
dataSetBackgroundColor7 = "#53629E"
dataSetErrorColor7 = "#0F0F5C"
dataSetLegendColor7 = "#0F0F5C"
dataSetRowTitleColor7 = "#0F0F5C"
dataSetBarFillColor8 = "#2C8AAE"
dataSetBarPatternColor8 = "#2C8AAE"
dataSetFillColor8 = "#2C8AAE"
dataSetLineColor8 = "#0E405C"
dataSetBorderColor8 = "#0E405C"
dataSetBackgroundColor8 = "#2C8AAE"
dataSetErrorColor8 = "#0E405C"
dataSetLegendColor8 = "#0E405C"
dataSetRowTitleColor8 = "#0E405C"
dataSetBarFillColor9 = "#51A278"
dataSetBarPatternColor9 = "#51A278"
dataSetFillColor9 = "#51A278"
dataSetLineColor9 = "#0B5C2D"
dataSetBorderColor9 = "#0B5C2D"
dataSetBackgroundColor9 = "#51A278"
dataSetErrorColor9 = "#0B5C2D"
dataSetLegendColor9 = "#0B5C2D"
dataSetRowTitleColor9 = "#0B5C2D"
dataSetBarFillColor10 = "#9CB667"
dataSetBarPatternColor10 = "#9CB667"
dataSetFillColor10 = "#9CB667"
dataSetLineColor10 = "#285C08"
dataSetBorderColor10 = "#285C08"
dataSetBackgroundColor10 = "#9CB667"
dataSetErrorColor10 = "#285C08"
dataSetLegendColor10 = "#285C08"
dataSetRowTitleColor10 = "#285C08"
