pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#993300"
axisLabelColor = "#993300"
axisTitleColor = "#993300"
graphTitleColor = "#008000"
objectTextColor = "#008000"
objectFillColor = "#FFFFFF"
objectBorderColor = "#008000"
objectLinesColor = "#33CC00"
objectPatternColor = "#33CC00"
embeddedTableBorderColor = "#6699CC"
embeddedTableLineUnderTitleColor = "#6699CC"
embeddedTableLineNextToRowTitleColor = "#6699CC"
embeddedTableTextColor = "#29547E"
embeddedTableGridColor = "#6699CC"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#33CC00"
dataSetBarPatternColor1 = "#33CC00"
dataSetFillColor1 = "#33CC00"
dataSetLineColor1 = "#33CC00"
dataSetBorderColor1 = "#008000"
dataSetBackgroundColor1 = "#33CC00"
dataSetErrorColor1 = "#008000"
dataSetLegendColor1 = "#33CC00"
dataSetRowTitleColor1 = "#000000"
dataSetBarFillColor2 = "#CC9900"
dataSetBarPatternColor2 = "#CC9900"
dataSetFillColor2 = "#CC9900"
dataSetLineColor2 = "#CC9900"
dataSetBorderColor2 = "#8B4513"
dataSetBackgroundColor2 = "#CC9900"
dataSetErrorColor2 = "#8B4513"
dataSetLegendColor2 = "#CC9900"
dataSetRowTitleColor2 = "#000000"
dataSetBarFillColor3 = "#6699CC"
dataSetBarPatternColor3 = "#6699CC"
dataSetFillColor3 = "#6699CC"
dataSetLineColor3 = "#6699CC"
dataSetBorderColor3 = "#6699CC"
dataSetBackgroundColor3 = "#6699CC"
dataSetErrorColor3 = "#6699CC"
dataSetLegendColor3 = "#6699CC"
dataSetRowTitleColor3 = "#000000"
dataSetBarFillColor4 = "#8B4513"
dataSetBarPatternColor4 = "#8B4513"
dataSetFillColor4 = "#8B4513"
dataSetLineColor4 = "#8B4513"
dataSetBorderColor4 = "#8B4513"
dataSetBackgroundColor4 = "#8B4513"
dataSetErrorColor4 = "#8B4513"
dataSetLegendColor4 = "#8B4513"
dataSetRowTitleColor4 = "#000000"
dataSetBarFillColor5 = "#90EE90"
dataSetBarPatternColor5 = "#90EE90"
dataSetFillColor5 = "#90EE90"
dataSetLineColor5 = "#90EE90"
dataSetBorderColor5 = "#33CC00"
dataSetBackgroundColor5 = "#90EE90"
dataSetErrorColor5 = "#33CC00"
dataSetLegendColor5 = "#008000"
dataSetRowTitleColor5 = "#000000"
dataSetBarFillColor6 = "#008000"
dataSetBarPatternColor6 = "#008000"
dataSetFillColor6 = "#008000"
dataSetLineColor6 = "#008000"
dataSetBorderColor6 = "#008000"
dataSetBackgroundColor6 = "#008000"
dataSetErrorColor6 = "#008000"
dataSetLegendColor6 = "#008000"
dataSetRowTitleColor6 = "#000000"
dataSetBarFillColor7 = "#CC9900"
dataSetBarPatternColor7 = "#CC9900"
dataSetFillColor7 = "#CC9900"
dataSetLineColor7 = "#CC9900"
dataSetBorderColor7 = "#CC9900"
dataSetBackgroundColor7 = "#CC9900"
dataSetErrorColor7 = "#8B4513"
dataSetLegendColor7 = "#CC9900"
dataSetRowTitleColor7 = "#000000"
dataSetBarFillColor8 = "#FFCC00"
dataSetBarPatternColor8 = "#FFCC00"
dataSetFillColor8 = "#FFCC00"
dataSetLineColor8 = "#FFCC00"
dataSetBorderColor8 = "#FFCC00"
dataSetBackgroundColor8 = "#FFCC00"
dataSetErrorColor8 = "#FFCC00"
dataSetLegendColor8 = "#FF9900"
dataSetRowTitleColor8 = "#000000"
dataSetBarFillColor9 = "#FFFF33"
dataSetBarPatternColor9 = "#FFFF33"
dataSetFillColor9 = "#FFFF33"
dataSetLineColor9 = "#FFFF33"
dataSetBorderColor9 = "#FFCC00"
dataSetBackgroundColor9 = "#FFFF33"
dataSetErrorColor9 = "#FFCC00"
dataSetLegendColor9 = "#FFFF33"
dataSetRowTitleColor9 = "#000000"
