pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#000080"
axisLabelColor = "#000080"
axisTitleColor = "#000080"
graphTitleColor = "#000080"
objectTextColor = "#000080"
objectFillColor = "#FFFFFF"
objectBorderColor = "#000080"
objectLinesColor = "#000080"
objectPatternColor = "#000080"
embeddedTableBorderColor = "#000080"
embeddedTableLineUnderTitleColor = "#000080"
embeddedTableLineNextToRowTitleColor = "#000080"
embeddedTableTextColor = "#000080"
embeddedTableGridColor = "#000080"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#000080"
dataSetBarPatternColor1 = "#000080"
dataSetFillColor1 = "#000080"
dataSetLineColor1 = "#000080"
dataSetBorderColor1 = "#000080"
dataSetBackgroundColor1 = "#000080"
dataSetErrorColor1 = "#000080"
dataSetLegendColor1 = "#0000C0"
dataSetRowTitleColor1 = "#0000C0"
dataSetBarFillColor2 = "#0000C0"
dataSetBarPatternColor2 = "#0000C0"
dataSetFillColor2 = "#0000C0"
dataSetLineColor2 = "#0000C0"
dataSetBorderColor2 = "#0000C0"
dataSetBackgroundColor2 = "#0000C0"
dataSetErrorColor2 = "#0000C0"
dataSetLegendColor2 = "#0000C0"
dataSetRowTitleColor2 = "#0000C0"
dataSetBarFillColor3 = "#0000FF"
dataSetBarPatternColor3 = "#0000FF"
dataSetFillColor3 = "#0000FF"
dataSetLineColor3 = "#0000FF"
dataSetBorderColor3 = "#0000FF"
dataSetBackgroundColor3 = "#0000FF"
dataSetErrorColor3 = "#0000FF"
dataSetLegendColor3 = "#0000C0"
dataSetRowTitleColor3 = "#0000C0"
dataSetBarFillColor4 = "#5757F9"
dataSetBarPatternColor4 = "#5757F9"
dataSetFillColor4 = "#5757F9"
dataSetLineColor4 = "#5757F9"
dataSetBorderColor4 = "#5757F9"
dataSetBackgroundColor4 = "#5757F9"
dataSetErrorColor4 = "#5757F9"
dataSetLegendColor4 = "#0000C0"
dataSetRowTitleColor4 = "#0000C0"
dataSetBarFillColor5 = "#55A0FB"
dataSetBarPatternColor5 = "#55A0FB"
dataSetFillColor5 = "#55A0FB"
dataSetLineColor5 = "#55A0FB"
dataSetBorderColor5 = "#55A0FB"
dataSetBackgroundColor5 = "#55A0FB"
dataSetErrorColor5 = "#55A0FB"
dataSetLegendColor5 = "#0000C0"
dataSetRowTitleColor5 = "#0000C0"
dataSetBarFillColor6 = "#90BFF9"
dataSetBarPatternColor6 = "#90BFF9"
dataSetFillColor6 = "#90BFF9"
dataSetLineColor6 = "#90BFF9"
dataSetBorderColor6 = "#90BFF9"
dataSetBackgroundColor6 = "#90BFF9"
dataSetErrorColor6 = "#90BFF9"
dataSetLegendColor6 = "#0000C0"
dataSetRowTitleColor6 = "#0000C0"
dataSetBarFillColor7 = "#C8DEF9"
dataSetBarPatternColor7 = "#C8DEF9"
dataSetFillColor7 = "#C8DEF9"
dataSetLineColor7 = "#C8DEF9"
dataSetBorderColor7 = "#C8DEF9"
dataSetBackgroundColor7 = "#C8DEF9"
dataSetErrorColor7 = "#C8DEF9"
dataSetLegendColor7 = "#0000C0"
dataSetRowTitleColor7 = "#0000C0"
dataSetBarFillColor8 = "#0000FF"
dataSetBarPatternColor8 = "#0000FF"
dataSetFillColor8 = "#0000FF"
dataSetLineColor8 = "#0000FF"
dataSetBorderColor8 = "#0000FF"
dataSetBackgroundColor8 = "#0000FF"
dataSetErrorColor8 = "#0000FF"
dataSetLegendColor8 = "#0000C0"
dataSetRowTitleColor8 = "#0000C0"
dataSetBarFillColor9 = "#5757F9"
dataSetBarPatternColor9 = "#5757F9"
dataSetFillColor9 = "#5757F9"
dataSetLineColor9 = "#5757F9"
dataSetBorderColor9 = "#5757F9"
dataSetBackgroundColor9 = "#5757F9"
dataSetErrorColor9 = "#5757F9"
dataSetLegendColor9 = "#0000C0"
dataSetRowTitleColor9 = "#0000C0"
