pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#000000"
axisLabelColor = "#000000"
axisTitleColor = "#000000"
graphTitleColor = "#000000"
objectTextColor = "#000000"
objectFillColor = "#FFFFFF"
objectBorderColor = "#000000"
objectLinesColor = "#000000"
objectPatternColor = "#000000"
embeddedTableBorderColor = "#000000"
embeddedTableLineUnderTitleColor = "#000000"
embeddedTableLineNextToRowTitleColor = "#000000"
embeddedTableTextColor = "#000000"
embeddedTableGridColor = "#000000"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#440154"
dataSetBarPatternColor1 = "#440154"
dataSetFillColor1 = "#440154"
dataSetLineColor1 = "#440154"
dataSetBorderColor1 = "#000000"
dataSetBackgroundColor1 = "#440154"
dataSetErrorColor1 = "#000000"
dataSetLegendColor1 = "#000000"
dataSetRowTitleColor1 = "#440154"
dataSetBarFillColor2 = "#414487"
dataSetBarPatternColor2 = "#414487"
dataSetFillColor2 = "#414487"
dataSetLineColor2 = "#414487"
dataSetBorderColor2 = "#000000"
dataSetBackgroundColor2 = "#414487"
dataSetErrorColor2 = "#000000"
dataSetLegendColor2 = "#000000"
dataSetRowTitleColor2 = "#414487"
dataSetBarFillColor3 = "#2A788E"
dataSetBarPatternColor3 = "#2A788E"
dataSetFillColor3 = "#2A788E"
dataSetLineColor3 = "#2A788E"
dataSetBorderColor3 = "#000000"
dataSetBackgroundColor3 = "#2A788E"
dataSetErrorColor3 = "#000000"
dataSetLegendColor3 = "#000000"
dataSetRowTitleColor3 = "#2A788E"
dataSetBarFillColor4 = "#22A884"
dataSetBarPatternColor4 = "#22A884"
dataSetFillColor4 = "#22A884"
dataSetLineColor4 = "#22A884"
dataSetBorderColor4 = "#000000"
dataSetBackgroundColor4 = "#22A884"
dataSetErrorColor4 = "#000000"
dataSetLegendColor4 = "#000000"
dataSetRowTitleColor4 = "#22A884"
dataSetBarFillColor5 = "#7AD151"
dataSetBarPatternColor5 = "#7AD151"
dataSetFillColor5 = "#7AD151"
dataSetLineColor5 = "#7AD151"
dataSetBorderColor5 = "#000000"
dataSetBackgroundColor5 = "#7AD151"
dataSetErrorColor5 = "#000000"
dataSetLegendColor5 = "#000000"
dataSetRowTitleColor5 = "#7AD151"
dataSetBarFillColor6 = "#FDE725"
dataSetBarPatternColor6 = "#FDE725"
dataSetFillColor6 = "#FDE725"
dataSetLineColor6 = "#FDE725"
dataSetBorderColor6 = "#000000"
dataSetBackgroundColor6 = "#FDE725"
dataSetErrorColor6 = "#000000"
dataSetLegendColor6 = "#000000"
dataSetRowTitleColor6 = "#FDE725"
