pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#666699"
axisLabelColor = "#666699"
axisTitleColor = "#666699"
graphTitleColor = "#666699"
objectTextColor = "#666699"
objectFillColor = "#FFFFFF"
objectBorderColor = "#666699"
objectLinesColor = "#666699"
objectPatternColor = "#90BFF9"
embeddedTableBorderColor = "#666699"
embeddedTableLineUnderTitleColor = "#666699"
embeddedTableLineNextToRowTitleColor = "#666699"
embeddedTableTextColor = "#666699"
embeddedTableGridColor = "#666699"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#99CCFF"
dataSetBarPatternColor1 = "#99CCFF"
dataSetFillColor1 = "#99CCFF"
dataSetLineColor1 = "#99CCFF"
dataSetBorderColor1 = "#99CCFF"
dataSetBackgroundColor1 = "#99CCFF"
dataSetErrorColor1 = "#99CCFF"
dataSetLegendColor1 = "#666699"
dataSetRowTitleColor1 = "#000000"
dataSetBarFillColor2 = "#CCCCFF"
dataSetBarPatternColor2 = "#CCCCFF"
dataSetFillColor2 = "#CCCCFF"
dataSetLineColor2 = "#CCCCFF"
dataSetBorderColor2 = "#CCCCFF"
dataSetBackgroundColor2 = "#CCCCFF"
dataSetErrorColor2 = "#CCCCFF"
dataSetLegendColor2 = "#666699"
dataSetRowTitleColor2 = "#000000"
dataSetBarFillColor3 = "#FFD700"
dataSetBarPatternColor3 = "#FFD700"
dataSetFillColor3 = "#FFD700"
dataSetLineColor3 = "#FFD700"
dataSetBorderColor3 = "#FFD700"
dataSetBackgroundColor3 = "#FFD700"
dataSetErrorColor3 = "#FFD700"
dataSetLegendColor3 = "#666699"
dataSetRowTitleColor3 = "#000000"
dataSetBarFillColor4 = "#00CCCC"
dataSetBarPatternColor4 = "#00CCCC"
dataSetFillColor4 = "#00CCCC"
dataSetLineColor4 = "#00CCCC"
dataSetBorderColor4 = "#00CCCC"
dataSetBackgroundColor4 = "#00CCCC"
dataSetErrorColor4 = "#00CCCC"
dataSetLegendColor4 = "#666699"
dataSetRowTitleColor4 = "#000000"
dataSetBarFillColor5 = "#AFEEEE"
dataSetBarPatternColor5 = "#AFEEEE"
dataSetFillColor5 = "#AFEEEE"
dataSetLineColor5 = "#AFEEEE"
dataSetBorderColor5 = "#AFEEEE"
dataSetBackgroundColor5 = "#AFEEEE"
dataSetErrorColor5 = "#00CCCC"
dataSetLegendColor5 = "#666699"
dataSetRowTitleColor5 = "#000000"
dataSetBarFillColor6 = "#FF99FF"
dataSetBarPatternColor6 = "#FF99FF"
dataSetFillColor6 = "#FF99FF"
dataSetLineColor6 = "#FF99FF"
dataSetBorderColor6 = "#FF99FF"
dataSetBackgroundColor6 = "#FF99FF"
dataSetErrorColor6 = "#FF99FF"
dataSetLegendColor6 = "#666699"
dataSetRowTitleColor6 = "#000000"
dataSetBarFillColor7 = "#FF9999"
dataSetBarPatternColor7 = "#FF9999"
dataSetFillColor7 = "#FF9999"
dataSetLineColor7 = "#FF9999"
dataSetBorderColor7 = "#FF9999"
dataSetBackgroundColor7 = "#FF9999"
dataSetErrorColor7 = "#FF9999"
dataSetLegendColor7 = "#666699"
dataSetRowTitleColor7 = "#000000"
dataSetBarFillColor8 = "#FFFF99"
dataSetBarPatternColor8 = "#FFFF99"
dataSetFillColor8 = "#FFFF99"
dataSetLineColor8 = "#FFD700"
dataSetBorderColor8 = "#FFD700"
dataSetBackgroundColor8 = "#FFFF99"
dataSetErrorColor8 = "#FFD700"
dataSetLegendColor8 = "#666699"
dataSetRowTitleColor8 = "#000000"
dataSetBarFillColor9 = "#99FFCC"
dataSetBarPatternColor9 = "#99FFCC"
dataSetFillColor9 = "#99FFCC"
dataSetLineColor9 = "#99FFCC"
dataSetBorderColor9 = "#99FFCC"
dataSetBackgroundColor9 = "#99FFCC"
dataSetErrorColor9 = "#00CCCC"
dataSetLegendColor9 = "#666699"
dataSetRowTitleColor9 = "#000000"
