pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#A00000"
axisLabelColor = "#A00000"
axisTitleColor = "#A00000"
graphTitleColor = "#A00000"
objectTextColor = "#27273D"
objectFillColor = "#FFFFFF"
objectBorderColor = "#000000"
objectLinesColor = "#000000"
objectPatternColor = "#000000"
embeddedTableBorderColor = "#000000"
embeddedTableLineUnderTitleColor = "#000000"
embeddedTableLineNextToRowTitleColor = "#000000"
embeddedTableTextColor = "#000000"
embeddedTableGridColor = "#000000"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#F94040"
dataSetBarPatternColor1 = "#F94040"
dataSetFillColor1 = "#F94040"
dataSetLineColor1 = "#F94040"
dataSetBorderColor1 = "#000000"
dataSetBackgroundColor1 = "#F94040"
dataSetErrorColor1 = "#F94040"
dataSetLegendColor1 = "#A00000"
dataSetRowTitleColor1 = "#A00000"
dataSetBarFillColor2 = "#FF6000"
dataSetBarPatternColor2 = "#FF8000"
dataSetFillColor2 = "#FF6000"
dataSetLineColor2 = "#FF6000"
dataSetBorderColor2 = "#000000"
dataSetBackgroundColor2 = "#FF8000"
dataSetErrorColor2 = "#FF6000"
dataSetLegendColor2 = "#A00000"
dataSetRowTitleColor2 = "#A00000"
dataSetBarFillColor3 = "#FFFF06"
dataSetBarPatternColor3 = "#FFFF00"
dataSetFillColor3 = "#FFFF06"
dataSetLineColor3 = "#FFFF06"
dataSetBorderColor3 = "#000000"
dataSetBackgroundColor3 = "#FFFF00"
dataSetErrorColor3 = "#FFFF06"
dataSetLegendColor3 = "#A00000"
dataSetRowTitleColor3 = "#A00000"
dataSetBarFillColor4 = "#FCA92E"
dataSetBarPatternColor4 = "#FCA92E"
dataSetFillColor4 = "#FCA92E"
dataSetLineColor4 = "#FCA92E"
dataSetBorderColor4 = "#000000"
dataSetBackgroundColor4 = "#FCA92E"
dataSetErrorColor4 = "#FCA92E"
dataSetLegendColor4 = "#A00000"
dataSetRowTitleColor4 = "#A00000"
dataSetBarFillColor5 = "#000000"
dataSetBarPatternColor5 = "#FFFFA0"
dataSetFillColor5 = "#000000"
dataSetLineColor5 = "#000000"
dataSetBorderColor5 = "#000000"
dataSetBackgroundColor5 = "#FFFFA0"
dataSetErrorColor5 = "#000000"
dataSetLegendColor5 = "#A00000"
dataSetRowTitleColor5 = "#A00000"
dataSetBarFillColor6 = "#F94040"
dataSetBarPatternColor6 = "#F94040"
dataSetFillColor6 = "#F94040"
dataSetLineColor6 = "#F94040"
dataSetBorderColor6 = "#000000"
dataSetBackgroundColor6 = "#F94040"
dataSetErrorColor6 = "#F94040"
dataSetLegendColor6 = "#A00000"
dataSetRowTitleColor6 = "#A00000"
dataSetBarFillColor7 = "#FFC080"
dataSetBarPatternColor7 = "#F2B77C"
dataSetFillColor7 = "#FFC080"
dataSetLineColor7 = "#FFC080"
dataSetBorderColor7 = "#000000"
dataSetBackgroundColor7 = "#F2B77C"
dataSetErrorColor7 = "#FFC080"
dataSetLegendColor7 = "#A00000"
dataSetRowTitleColor7 = "#A00000"
dataSetBarFillColor8 = "#FF8000"
dataSetBarPatternColor8 = "#FF8000"
dataSetFillColor8 = "#FF8000"
dataSetLineColor8 = "#FF8000"
dataSetBorderColor8 = "#000000"
dataSetBackgroundColor8 = "#FF8000"
dataSetErrorColor8 = "#FF8000"
dataSetLegendColor8 = "#A00000"
dataSetRowTitleColor8 = "#A00000"
dataSetBarFillColor9 = "#CE0665"
dataSetBarPatternColor9 = "#CE0665"
dataSetFillColor9 = "#CE0665"
dataSetLineColor9 = "#CE0665"
dataSetBorderColor9 = "#000000"
dataSetBackgroundColor9 = "#CE0665"
dataSetErrorColor9 = "#CE0665"
dataSetLegendColor9 = "#A00000"
dataSetRowTitleColor9 = "#A00000"
