pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#000000"
axisLabelColor = "#000000"
axisTitleColor = "#000000"
graphTitleColor = "#000000"
objectTextColor = "#000000"
objectFillColor = "#FFFFFF"
objectBorderColor = "#000000"
objectLinesColor = "#000000"
objectPatternColor = "#000000"
embeddedTableBorderColor = "#000000"
embeddedTableLineUnderTitleColor = "#000000"
embeddedTableLineNextToRowTitleColor = "#000000"
embeddedTableTextColor = "#000000"
embeddedTableGridColor = "#000000"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#2E58A4"
dataSetBarPatternColor1 = "#2E58A4"
dataSetFillColor1 = "#2E58A4"
dataSetLineColor1 = "#2E58A4"
dataSetBorderColor1 = "#031431"
dataSetBackgroundColor1 = "#2E58A4"
dataSetErrorColor1 = "#031431"
dataSetLegendColor1 = "#000000"
dataSetRowTitleColor1 = "#000000"
dataSetBarFillColor2 = "#B69D71"
dataSetBarPatternColor2 = "#B69D71"
dataSetFillColor2 = "#B69D71"
dataSetLineColor2 = "#B69D71"
dataSetBorderColor2 = "#6F5A35"
dataSetBackgroundColor2 = "#B69D71"
dataSetErrorColor2 = "#6F5A35"
dataSetLegendColor2 = "#000000"
dataSetRowTitleColor2 = "#000000"
dataSetBarFillColor3 = "#E3DED4"
dataSetBarPatternColor3 = "#E3DED4"
dataSetFillColor3 = "#E3DED4"
dataSetLineColor3 = "#E3DED4"
dataSetBorderColor3 = "#63615D"
dataSetBackgroundColor3 = "#E3DED4"
dataSetErrorColor3 = "#63615D"
dataSetLegendColor3 = "#000000"
dataSetRowTitleColor3 = "#000000"
dataSetBarFillColor4 = "#70AFC7"
dataSetBarPatternColor4 = "#70AFC7"
dataSetFillColor4 = "#70AFC7"
dataSetLineColor4 = "#70AFC7"
dataSetBorderColor4 = "#33565F"
dataSetBackgroundColor4 = "#70AFC7"
dataSetErrorColor4 = "#33565F"
dataSetLegendColor4 = "#000000"
dataSetRowTitleColor4 = "#000000"
dataSetBarFillColor5 = "#4F5357"
dataSetBarPatternColor5 = "#4F5357"
dataSetFillColor5 = "#4F5357"
dataSetLineColor5 = "#4F5357"
dataSetBorderColor5 = "#27292B"
dataSetBackgroundColor5 = "#4F5357"
dataSetErrorColor5 = "#27292B"
dataSetLegendColor5 = "#000000"
dataSetRowTitleColor5 = "#000000"
