pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#000080"
axisLabelColor = "#000080"
axisTitleColor = "#000080"
graphTitleColor = "#000080"
objectTextColor = "#76069A"
objectFillColor = "#FFFFFF"
objectBorderColor = "#000080"
objectLinesColor = "#000080"
objectPatternColor = "#000080"
embeddedTableBorderColor = "#000080"
embeddedTableLineUnderTitleColor = "#000080"
embeddedTableLineNextToRowTitleColor = "#000080"
embeddedTableTextColor = "#000080"
embeddedTableGridColor = "#000080"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#077E97"
dataSetBarPatternColor1 = "#0F99B2"
dataSetFillColor1 = "#077E97"
dataSetLineColor1 = "#077E97"
dataSetBorderColor1 = "#077E97"
dataSetBackgroundColor1 = "#0F99B2"
dataSetErrorColor1 = "#077E97"
dataSetLegendColor1 = "#000080"
dataSetRowTitleColor1 = "#000080"
dataSetBarFillColor2 = "#800080"
dataSetBarPatternColor2 = "#C000C0"
dataSetFillColor2 = "#800080"
dataSetLineColor2 = "#800080"
dataSetBorderColor2 = "#800080"
dataSetBackgroundColor2 = "#C000C0"
dataSetErrorColor2 = "#800080"
dataSetLegendColor2 = "#000080"
dataSetRowTitleColor2 = "#000080"
dataSetBarFillColor3 = "#000080"
dataSetBarPatternColor3 = "#0000C0"
dataSetFillColor3 = "#000080"
dataSetLineColor3 = "#000080"
dataSetBorderColor3 = "#000080"
dataSetBackgroundColor3 = "#0000C0"
dataSetErrorColor3 = "#000080"
dataSetLegendColor3 = "#000080"
dataSetRowTitleColor3 = "#000080"
dataSetBarFillColor4 = "#8D8DFF"
dataSetBarPatternColor4 = "#90BFF9"
dataSetFillColor4 = "#8D8DFF"
dataSetLineColor4 = "#8D8DFF"
dataSetBorderColor4 = "#8D8DFF"
dataSetBackgroundColor4 = "#90BFF9"
dataSetErrorColor4 = "#8D8DFF"
dataSetLegendColor4 = "#000080"
dataSetRowTitleColor4 = "#000080"
dataSetBarFillColor5 = "#C000C0"
dataSetBarPatternColor5 = "#B07FC0"
dataSetFillColor5 = "#C000C0"
dataSetLineColor5 = "#C000C0"
dataSetBorderColor5 = "#C000C0"
dataSetBackgroundColor5 = "#B07FC0"
dataSetErrorColor5 = "#C000C0"
dataSetLegendColor5 = "#000080"
dataSetRowTitleColor5 = "#000080"
dataSetBarFillColor6 = "#056943"
dataSetBarPatternColor6 = "#099963"
dataSetFillColor6 = "#056943"
dataSetLineColor6 = "#056943"
dataSetBorderColor6 = "#056943"
dataSetBackgroundColor6 = "#099963"
dataSetErrorColor6 = "#056943"
dataSetLegendColor6 = "#000080"
dataSetRowTitleColor6 = "#000080"
dataSetBarFillColor7 = "#077E97"
dataSetBarPatternColor7 = "#0F99B2"
dataSetFillColor7 = "#077E97"
dataSetLineColor7 = "#077E97"
dataSetBorderColor7 = "#077E97"
dataSetBackgroundColor7 = "#0F99B2"
dataSetErrorColor7 = "#077E97"
dataSetLegendColor7 = "#000080"
dataSetRowTitleColor7 = "#000080"
dataSetBarFillColor8 = "#800080"
dataSetBarPatternColor8 = "#C000C0"
dataSetFillColor8 = "#800080"
dataSetLineColor8 = "#800080"
dataSetBorderColor8 = "#800080"
dataSetBackgroundColor8 = "#C000C0"
dataSetErrorColor8 = "#800080"
dataSetLegendColor8 = "#000080"
dataSetRowTitleColor8 = "#000080"
dataSetBarFillColor9 = "#000080"
dataSetBarPatternColor9 = "#0000C0"
dataSetFillColor9 = "#000080"
dataSetLineColor9 = "#000080"
dataSetBorderColor9 = "#000080"
dataSetBackgroundColor9 = "#0000C0"
dataSetErrorColor9 = "#000080"
dataSetLegendColor9 = "#000080"
dataSetRowTitleColor9 = "#000080"
