pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#0000C0"
axisLabelColor = "#0000C0"
axisTitleColor = "#0000C0"
graphTitleColor = "#0000C0"
objectTextColor = "#0000C0"
objectFillColor = "#FFFFFF"
objectBorderColor = "#0000C0"
objectLinesColor = "#0000C0"
objectPatternColor = "#0000C0"
embeddedTableBorderColor = "#0000C0"
embeddedTableLineUnderTitleColor = "#0000C0"
embeddedTableLineNextToRowTitleColor = "#0000C0"
embeddedTableTextColor = "#0000C0"
embeddedTableGridColor = "#0000C0"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#55A0FB"
dataSetBarPatternColor1 = "#55A0FB"
dataSetFillColor1 = "#55A0FB"
dataSetLineColor1 = "#55A0FB"
dataSetBorderColor1 = "#55A0FB"
dataSetBackgroundColor1 = "#55A0FB"
dataSetErrorColor1 = "#55A0FB"
dataSetLegendColor1 = "#0000C0"
dataSetRowTitleColor1 = "#0000C0"
dataSetBarFillColor2 = "#F74ED6"
dataSetBarPatternColor2 = "#F74ED6"
dataSetFillColor2 = "#F74ED6"
dataSetLineColor2 = "#F74ED6"
dataSetBorderColor2 = "#F74ED6"
dataSetBackgroundColor2 = "#F74ED6"
dataSetErrorColor2 = "#F74ED6"
dataSetLegendColor2 = "#0000C0"
dataSetRowTitleColor2 = "#0000C0"
dataSetBarFillColor3 = "#5757F9"
dataSetBarPatternColor3 = "#5757F9"
dataSetFillColor3 = "#5757F9"
dataSetLineColor3 = "#5757F9"
dataSetBorderColor3 = "#5757F9"
dataSetBackgroundColor3 = "#5757F9"
dataSetErrorColor3 = "#5757F9"
dataSetLegendColor3 = "#0000C0"
dataSetRowTitleColor3 = "#0000C0"
dataSetBarFillColor4 = "#C8DEF9"
dataSetBarPatternColor4 = "#C8DEF9"
dataSetFillColor4 = "#C8DEF9"
dataSetLineColor4 = "#C8DEF9"
dataSetBorderColor4 = "#C8DEF9"
dataSetBackgroundColor4 = "#C8DEF9"
dataSetErrorColor4 = "#C8DEF9"
dataSetLegendColor4 = "#0000C0"
dataSetRowTitleColor4 = "#0000C0"
dataSetBarFillColor5 = "#DE8BF9"
dataSetBarPatternColor5 = "#DE8BF9"
dataSetFillColor5 = "#DE8BF9"
dataSetLineColor5 = "#DE8BF9"
dataSetBorderColor5 = "#DE8BF9"
dataSetBackgroundColor5 = "#DE8BF9"
dataSetErrorColor5 = "#DE8BF9"
dataSetLegendColor5 = "#0000C0"
dataSetRowTitleColor5 = "#0000C0"
dataSetBarFillColor6 = "#05BE78"
dataSetBarPatternColor6 = "#05BE78"
dataSetFillColor6 = "#05BE78"
dataSetLineColor6 = "#05BE78"
dataSetBorderColor6 = "#05BE78"
dataSetBackgroundColor6 = "#05BE78"
dataSetErrorColor6 = "#05BE78"
dataSetLegendColor6 = "#0000C0"
dataSetRowTitleColor6 = "#0000C0"
dataSetBarFillColor7 = "#90BFF9"
dataSetBarPatternColor7 = "#90BFF9"
dataSetFillColor7 = "#90BFF9"
dataSetLineColor7 = "#90BFF9"
dataSetBorderColor7 = "#90BFF9"
dataSetBackgroundColor7 = "#90BFF9"
dataSetErrorColor7 = "#90BFF9"
dataSetLegendColor7 = "#0000C0"
dataSetRowTitleColor7 = "#0000C0"
dataSetBarFillColor8 = "#F7ABE8"
dataSetBarPatternColor8 = "#F7ABE8"
dataSetFillColor8 = "#F7ABE8"
dataSetLineColor8 = "#F7ABE8"
dataSetBorderColor8 = "#F7ABE8"
dataSetBackgroundColor8 = "#F7ABE8"
dataSetErrorColor8 = "#F7ABE8"
dataSetLegendColor8 = "#0000C0"
dataSetRowTitleColor8 = "#0000C0"
dataSetBarFillColor9 = "#8D8DFF"
dataSetBarPatternColor9 = "#8D8DFF"
dataSetFillColor9 = "#8D8DFF"
dataSetLineColor9 = "#8D8DFF"
dataSetBorderColor9 = "#8D8DFF"
dataSetBackgroundColor9 = "#8D8DFF"
dataSetErrorColor9 = "#8D8DFF"
dataSetLegendColor9 = "#0000C0"
dataSetRowTitleColor9 = "#0000C0"
