pageBackgroundColor = "#FFFFFF"
plottingAreaColor = "#FFFFFF"
axisColor = "#660099"
axisLabelColor = "#660099"
axisTitleColor = "#660099"
graphTitleColor = "#6699CC"
objectTextColor = "#6699CC"
objectFillColor = "#FFFFFF"
objectBorderColor = "#6699CC"
objectLinesColor = "#6699CC"
objectPatternColor = "#87CEFA"
embeddedTableBorderColor = "#87CEFA"
embeddedTableLineUnderTitleColor = "#87CEFA"
embeddedTableLineNextToRowTitleColor = "#87CEFA"
embeddedTableTextColor = "#6699CC"
embeddedTableGridColor = "#87CEFA"
embeddedTablePatternColor = "#FFFFFF"
embeddedTableFillColor = "#FFFFFF"
dataSetBarFillColor1 = "#6699CC"
dataSetBarPatternColor1 = "#6699CC"
dataSetFillColor1 = "#6699CC"
dataSetLineColor1 = "#6699CC"
dataSetBorderColor1 = "#6699CC"
dataSetBackgroundColor1 = "#6699CC"
dataSetErrorColor1 = "#6699CC"
dataSetLegendColor1 = "#6699CC"
dataSetRowTitleColor1 = "#000000"
dataSetBarFillColor2 = "#87CEFA"
dataSetBarPatternColor2 = "#87CEFA"
dataSetFillColor2 = "#87CEFA"
dataSetLineColor2 = "#87CEFA"
dataSetBorderColor2 = "#6699CC"
dataSetBackgroundColor2 = "#87CEFA"
dataSetErrorColor2 = "#87CEFA"
dataSetLegendColor2 = "#6699CC"
dataSetRowTitleColor2 = "#000000"
dataSetBarFillColor3 = "#FF9933"
dataSetBarPatternColor3 = "#FF9933"
dataSetFillColor3 = "#FF9933"
dataSetLineColor3 = "#FF9933"
dataSetBorderColor3 = "#FF9933"
dataSetBackgroundColor3 = "#FF9933"
dataSetErrorColor3 = "#FF9933"
dataSetLegendColor3 = "#6699CC"
dataSetRowTitleColor3 = "#000000"
dataSetBarFillColor4 = "#6699CC"
dataSetBarPatternColor4 = "#6699CC"
dataSetFillColor4 = "#6699CC"
dataSetLineColor4 = "#6699CC"
dataSetBorderColor4 = "#4169E1"
dataSetBackgroundColor4 = "#6699CC"
dataSetErrorColor4 = "#4169E1"
dataSetLegendColor4 = "#6699CC"
dataSetRowTitleColor4 = "#000000"
dataSetBarFillColor5 = "#87CEFA"
dataSetBarPatternColor5 = "#87CEFA"
dataSetFillColor5 = "#87CEFA"
dataSetLineColor5 = "#87CEFA"
dataSetBorderColor5 = "#87CEFA"
dataSetBackgroundColor5 = "#87CEFA"
dataSetErrorColor5 = "#87CEFA"
dataSetLegendColor5 = "#6699CC"
dataSetRowTitleColor5 = "#000000"
dataSetBarFillColor6 = "#FF6600"
dataSetBarPatternColor6 = "#FF6600"
dataSetFillColor6 = "#FF6600"
dataSetLineColor6 = "#FF6600"
dataSetBorderColor6 = "#FF6600"
dataSetBackgroundColor6 = "#FF6600"
dataSetErrorColor6 = "#FF6600"
dataSetLegendColor6 = "#6699CC"
dataSetRowTitleColor6 = "#000000"
dataSetBarFillColor7 = "#CCCCFF"
dataSetBarPatternColor7 = "#CCCCFF"
dataSetFillColor7 = "#CCCCFF"
dataSetLineColor7 = "#CCCCFF"
dataSetBorderColor7 = "#CCCCFF"
dataSetBackgroundColor7 = "#CCCCFF"
dataSetErrorColor7 = "#CCCCFF"
dataSetLegendColor7 = "#6699CC"
dataSetRowTitleColor7 = "#000000"
dataSetBarFillColor8 = "#87CEFA"
dataSetBarPatternColor8 = "#87CEFA"
dataSetFillColor8 = "#87CEFA"
dataSetLineColor8 = "#87CEFA"
dataSetBorderColor8 = "#6699CC"
dataSetBackgroundColor8 = "#87CEFA"
dataSetErrorColor8 = "#87CEFA"
dataSetLegendColor8 = "#6699CC"
dataSetRowTitleColor8 = "#000000"
dataSetBarFillColor9 = "#FF9933"
dataSetBarPatternColor9 = "#FF9933"
dataSetFillColor9 = "#FF9933"
dataSetLineColor9 = "#FF9933"
dataSetBorderColor9 = "#FF6600"
dataSetBackgroundColor9 = "#FF9933"
dataSetErrorColor9 = "#FF6600"
dataSetLegendColor9 = "#6699CC"
dataSetRowTitleColor9 = "#000000"
